### ISSUE TITLE
Listing resources using a label selector and chunk size returns unexpected result

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1099]
**Version:**
v1.0.0-rc5

**Describe the bug**
If you attempt to list resources across all namespaces using a label selector and and specifying chunk size, no results will be returned

**To Reproduce**
1. Create at least three resources with differing labels, for example a simple configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: test1
  name: foo
  namespace: default

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: test2
  name: bar
  namespace: default

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: test3
  name: bing
  namespace: default
```

Perform the following gets for each label that you specified:
```
kubectl get configmap -A -l 'app=test1'
kubectl get configmap -A -l 'app=test1' --chunk-size=1
kubectl get configmap -n default -l 'app=test1'

kubectl get configmap -A -l 'app=test2'
kubectl get configmap -A -l 'app=test2' --chunk-size=1
kubectl get configmap -n default -l 'app=test2'

kubectl get configmap -A -l 'app=test3'
kubectl get configmap -A -l 'app=test3' --chunk-size=1
kubectl get configmap -n default -l 'app=test3'
```

**Expected behavior**

For all three get's the output should be the same. They should all return a single result like:
```
kubectl get configmap -A -l 'app=test1'
NAMESPACE   NAME   DATA   AGE
default     bar    0      3m11s
en$ kubectl get configmap -A -l 'app=test1' --chunk-size=1
```

**Actual behavior**
Some of the gets return an empty result set
