### ISSUE TITLE
extra bind feature like rke and service_node_port_range?

### ISSUE THREAD

**Issue by segator** [rancher/k3s#1127]
How can I set up 
```
services:
    kube-api:
      service_node_port_range: 30000-32767
    kubelet:
      extra_binds:
        - "/mnt:/mnt:shared"
```
for k3s command line?

Thanks!
