### ISSUE TITLE
How to change the pause registry? The arg "--pause-image" does not work!

### ISSUE THREAD

**Issue by colben** [rancher/k3s#1176]
**Version:**
- k3s version v1.0.0 (18bd921c)
- command
    ```bash
    /usr/local/bin/k3s \
        server \
        --docker \
        --pause-image='10.0.16.124:5443/k3s/k8s.gcr.io/pause:3.1' \
        --no-deploy='servicelb,traefik,local-storage,metrics-server' \
        --datastore-endpoint='mysql://k3s:12345678@tcp(10.0.4.111:3306)/k3s'
    ```
- contents of /etc/rancher/k3s/registries.yaml
    ```yaml
    ---
    mirrors:
      customreg:
        endpoint:
        - "https://10.0.16.124:5443"
    configs:
      customreg:
        #auth:
        #  username: xxxxxx # this is the registry username
        #  password: xxxxxx # this is the registry password
        tls:
          cert_file: /etc/rancher/certs.d/10.0.16.124:5443/10.0.16.124.cert
          key_file: /etc/rancher/certs.d/10.0.16.124:5443/10.0.16.124.key
          ca_file: /etc/rancher/certs.d/10.0.16.124:5443/ca.crt
    ```

**Describe the bug**
- When started k3s server, k3s still tried to pull pause image from k8s.gcr.io, but not my private harbor registry "10.0.16.124:5443".
- Here is the "Events" from command "kubectl describe pod coredns-d798c9dd-lcksb -n kube-system"
    ```
    Events:
      Type     Reason                  Age        From                  Message
      ----     ------                  ----       ----                  -------
      Normal   Scheduled               <unknown>  default-scheduler     Successfully assigned kube-system/coredns-d798c9dd-lcksb to k3s-server0
      Warning  FailedCreatePodSandBox  7s         kubelet, k3s-server0  Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    ``` 

**To Reproduce**
- Just start k3s server with the command in 'Version' section.

**Expected behavior**
- K3s pulls pause image from my harbor registry directly, not connects to k8s.gcr.io any more, China mainland ...

**Actual behavior**
- K3s still tried to pull pause image from k8s.gcr.io

**Additional context**
- Nothing ...
