### ISSUE TITLE
Question: Error using nginx igress controller after traefik disabled

### ISSUE THREAD

**Issue by silverlight** [rancher/k3s#1201]
**Version:**
latest

**Describe the bug**
I want to replease nginx ingress controller with default traefik, I installed k3s with no deploy traefik then I installed ingress controller and apply a nginx ingress resource like this.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: my-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nginx1.beencoding.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx
          servicePort: 80
``` 
The ingress controller looks fine
![image](https://user-images.githubusercontent.com/18061452/70858578-5785ab00-1f3f-11ea-8e19-2e4b71992cd5.png)

And I can access my nginx service through cluster IP
![image](https://user-images.githubusercontent.com/18061452/70858593-a7647200-1f3f-11ea-8f49-e554dde9bed9.png)

**Expected behavior**
I can access my nginx service by nginx1.beencoding.com 

**Actual behavior**

![image](https://user-images.githubusercontent.com/18061452/70858586-8734b300-1f3f-11ea-9388-f61a51a5043c.png)

Am I miss anything?
