### ISSUE TITLE
unable to import k3s into rancher 

### ISSUE THREAD

**Issue by rshiva777** [rancher/k3s#1282]
root@ubuntuvm:~# k3s -v
k3s version v0.9.1 (755bd1c6)

I am trying to export my running k3s cluster into rancher. 2 pods are created inside the cluster and are running. But it is not exporting to rancher and throwing an error.

root@ubuntuvm:~# k3s kubectl get po -n cattle-system
NAME                                   READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-ccc78fdff-nrl5g   1/1     Running   0          93m
cattle-node-agent-nhqnq                1/1     Running   0          70m

The logs of cattle-node-agent-nhqnq    shows the below:

root@ubuntuvm:~# k3s kubectl  logs -f cattle-node-agent-nhqnq  -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.106.131.249 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=5ec318a427bd88ca2ac7d10c02dce6cbcd43679c611a57b3c4a74b3fec7b496c CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=ubuntuvm CATTLE_SERVER=https://10.106.131.249:9443
INFO: Using resolv.conf: nameserver 10.103.130.10 nameserver 10.150.5.29 nameserver 10.150.5.30 search hclt.corp.hcl.in
INFO: https://10.106.131.249:9443/ping is accessible
INFO: Value from https://10.106.131.249:9443/v3/settings/cacerts is an x509 certificate
time="2020-01-09T05:55:59Z" level=info msg="Rancher agent version v2.2.0 is starting"
time="2020-01-09T05:55:59Z" level=info msg="Option customConfig=map[address:10.106.131.249 internalAddress: roles:[] label:map[]]"
time="2020-01-09T05:55:59Z" level=info msg="Option etcd=false"
time="2020-01-09T05:55:59Z" level=info msg="Option controlPlane=false"
time="2020-01-09T05:55:59Z" level=info msg="Option worker=false"
time="2020-01-09T05:55:59Z" level=info msg="Option requestedHostname=ubuntuvm"
time="2020-01-09T05:55:59Z" level=info msg="Listening on /tmp/log.sock"
time="2020-01-09T05:55:59Z" level=info msg="Connecting to wss://10.106.131.249:9443/v3/connect with token vhxkklz558fl557j65zmmwttj4rdw8c2695pm4f4qfg99zz5qjw7cv"
time="2020-01-09T05:55:59Z" level=info msg="Connecting to proxy" url="wss://10.106.131.249:9443/v3/connect"
time="2020-01-09T05:55:59Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2020-01-09T05:55:59Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2020-01-09T05:56:09Z" level=info msg="Connecting to wss://10.106.131.249:9443/v3/connect with token vhxkklz558fl557j65zmmwttj4rdw8c2695pm4f4qfg99zz5qjw7cv"
time="2020-01-09T05:56:09Z" level=info msg="Connecting to proxy" url="wss://10.106.131.249:9443/v3/connect"
time="2020-01-09T05:56:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2020-01-09T05:56:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

Please check on this

**Comment by erikwilson** [comment]
Sorry this is an issue for you, are you able to connect to the Rancher server IP from the node or a test container?

**Comment by jeffkight** [comment]
I also have this problem.  
Failing scenario: rancher in docker and k3s cluster are on same network; an http proxy is required to access internet.  rancher can communicate via proxy with internet (running github authentication successfully), k3s can communicate via proxy with internet.  Import fails with similar logs.

Note, if rancher is running on a docker node on the internet, and I have local and proxy access via k3s, the import is successful.

This bug is still a problem in v2.3.5 of rancher.

**Comment by cjellick** [comment]
title should say import. i updated

**Comment by cjellick** [comment]
@jeffkight - what does "local and proxy access via k3s". Specifically, I'm not sure what you mean by local.

**Comment by jeffkight** [comment]
@cjellick i have two k3s clusters. One k3s cluster is behind a proxy, and the second k3s cluster is on the same subnet as the rancher docker instance. Both types of clusters import in this scenario... which has no proxy on the rancher docket image.

**Comment by cjellick** [comment]
Thanks. On more recent versions of Rancher, our logging got better when he hit the "bad handshake" problem. Can you share your agent logs to see if we get anything more useful out of them?

I'm not confident that this is a k3s issue. I wonder if it would happen with an RKE cluster. May be a more general rancher issue.

In your failing scenario, is the URL that the rancher-agent is attempting to reach rancher a public internet one or is it an address on the local network?

**Comment by cloudnautique** [comment]
@cjellick, I believe on an RKE based cluster you can configure the Docker daemon to setup for HTTP Proxy settings on all containers. I don't know if there is similar functionality in containerd that could be exposed. 

@jeffkight as a workaround, you might be able to edit the yaml provided by the Rancher server to manually include the HTTP_PROXY, HTTPS_PROXY and no_proxy settings. You have to do download the manifests and add envs to each of the two deployments, then kubectl apply the edited yaml.

**Comment by cjellick** [comment]
@cloudnautique I believe importing k3s is working with a proxy, just not when there is a proxy and rancher server and k3s are on the same network.

see:
> @cjellick i have two k3s clusters. One k3s cluster is behind a proxy, and the second k3s cluster is on the same subnet as the rancher docker instance. Both types of clusters import in this scenario... which has no proxy on the rancher docket image.

**Comment by cjellick** [comment]
Circling back to this, I'm awaiting more info from @jeffkight:
Previously asks:
- Can you share your agent logs to see if we get anything more useful out of them?
- In your failing scenario, is the URL that the rancher-agent is attempting to reach rancher a public internet one or is it an address on the local network?

New asks:
- What is the proxy technology being used?
- What version of k3s and rancher are you using?
- How have you configured Rancher and K3s to use the proxy? Sharing the actual bits of relevant configuration would be most useful.

**Comment by cjellick** [comment]
This may be related to (or a duplicate of) https://github.com/rancher/rancher/issues/24876. This issue (and the fix) identified that the rancher agents do not respect the HTTP(S)_PROXY environment variables.

It was just recently fixed and should be in v2.4.0 and the next 2.3.x release.

@jeffkight if you're interested, I could get a 2.3.6 alpha build out for you to test.

**Comment by davidnuzik** [comment]
I executed tests with various environmental configurations. When testing v2.3-head I noticed that I can't import any clusters if Rancher is behind a proxy. See https://github.com/rancher/rancher/issues/25372
I don't recall this working as well on Rancher v2.3.3 and will test v2.3.5 today.

**Comment by cjellick** [comment]
Summary of where we stand on this issue:

First, Rancher had a bug that prevented having a downstream cluster behind a proxy. That is this bug: https://github.com/rancher/rancher/issues/24876. It is fixed, but not in a release yet. Should be in the next v2.3.x release and in v2.4.0

Second, while working through reproducing the issue and testing the above fix, we identified another bug, this one: https://github.com/rancher/rancher/issues/25372. This bug states that importing a cluster doesn’t work if rancher is using a proxy.

This was all already mentioned above, just wanted to succinctly summarize.

**Comment by jeffkight** [comment]
@cjellick  and @davidnuzik, My apologies for the delay... have been out of the country on holiday.

My initial thoughts are that this is a rancher issue, not a k3s issue... due to if rancher is not in a proxy environment, I can successfully import proxied and non-proxied k3s environments.

I believe that I am configuring the proxy environment successfully for k3s, as I can pull images successfully.  I believe I am configuring the proxy environment successfully for rancher, as github authentication is functional.

Previous asks:

- Can you share your agent logs to see if we get anything more useful out of them?
> Attached logs from my session with Mark Abrams...
[k3s-infra1-apply.log](https://github.com/rancher/k3s/files/4200405/k3s-infra1-apply.log)
[rancher-docker.log](https://github.com/rancher/k3s/files/4200406/rancher-docker.log)

- In your failing scenario, is the URL that the rancher-agent is attempting to reach rancher a public internet one or is it an address on the local network?
> It is a private rancher address in the failing scenario, for either public k3s cluster *or* private k3s cluster -- both fail
> In contrast, if rancher has a public internet address, both public and private k3s clusters import successfully

New asks:

What is the proxy technology being used?
> I have requested the details for my lab... but this is failing both in my lab environment, and with a corporate telcom proxy implementation
What version of k3s and rancher are you using?
>   k3s_version: "v1.17.2+k3s1", although issue has existing from GA v1
>   it always has been latest... so up through v2.3.5

How have you configured Rancher and K3s to use the proxy? Sharing the actual bits of relevant configuration would be most useful.

Excerpt from Ansible rancher role:
```
vars:
  proxy: "http://proxy.ftc5.hpelabs.net:8080"
  no_proxy: "localhost,127.0.0.1,0.0.0.0,172.20.12.192/26,kightlabs.net,hpelabs.net"

tasks:
---
# tasks file for rancher

- name: create certs dir
  file:
    path: '{{ certs_dest_dir }}'
    state: directory
    mode: '0700'
  become: yes

- name: copy certs
  copy:
    src: '{{ item }}'
    dest: '{{ certs_dest_dir }}/'
    mode: '0600'
  become: yes
  loop: '{{ certs_list }}'

- name: start rancher in docker with certs, no proxy
  docker_container:
    name: myrancher
    image: rancher/rancher
    ports:
    - "80:80"
    - "443:443"
    restart_policy: unless-stopped
    volumes: '{{ volumes_list }}'
  become: yes
  when:
  - install_ca
  - not use_proxy

- name: start rancher in docker, no certs, no proxy
  docker_container:
    name: myrancher
    image: rancher/rancher
    ports:
    - "80:80"
    - "443:443"
    restart_policy: unless-stopped
  become: yes
  when:
  - not install_ca
  - not use_proxy

- name: start rancher in docker with certs, use proxy
  docker_container:
    name: myrancher
    image: rancher/rancher
    ports:
    - "80:80"
    - "443:443"
    restart_policy: unless-stopped
    volumes: '{{ volumes_list }}'
    env:
      HTTP_PROXY: "{{ proxy }}"
      HTTPS_PROXY: "{{ proxy }}"
      NO_PROXY: "{{ no_proxy }}"
      http_proxy: "{{ proxy }}"
      https_proxy: "{{ proxy }}"
      no_proxy: "{{ no_proxy }}"
  become: yes
  when:
  - install_ca
  - use_proxy

- name: start rancher in docker, use proxy, no certs
  docker_container:
    name: myrancher
    image: rancher/rancher
    ports:
    - "80:80"
    - "443:443"
    restart_policy: unless-stopped
    env:
      HTTP_PROXY: "{{ proxy }}"
      HTTPS_PROXY: "{{ proxy }}"
      NO_PROXY: "{{ no_proxy }}"
      http_proxy: "{{ proxy }}"
      https_proxy: "{{ proxy }}"
      no_proxy: "{{ no_proxy }}"
  become: yes
  when:
  - not install_ca
  - use_proxy

```
Excerpt from Ansible k3s-masters role:
```
vars:
  proxy: "http://proxy.ftc5.hpelabs.net:8080"
  no_proxy: "localhost,127.0.0.1,172.20.12.192/26,kightlabs.net,hpelabs.net"

tasks:
---
# tasks file for k3s-master

- name: create Downloads directory
  file:
    path: Downloads
    state: directory
    mode: '0755'

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: use_proxy

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  when: not use_proxy

- name: install k3s no proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_EXEC="{{ k3s_exec }} --node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: not use_proxy
  register: master_install_result
  become: yes

- name: results of installation
  debug: var=master_install_result
  when: master_install_result is changed

- name: install k3s with proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_EXEC="{{ k3s_exec }} --node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    HTTP_PROXY="{{ proxy }}" 
    HTTPS_PROXY="{{ proxy }}" 
    NO_PROXY="{{ no_proxy }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: use_proxy
  register: master_install_result
  become: yes

- name: results of installation
  debug: var=master_install_result
  when: master_install_result is changed

- name: create credentials directory on localhost
  file:
    path: credentials
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: fetch k3s.yaml
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes

- name: update master ip in k3s.yaml
  replace:
    path: "{{ kubeconfig }}"
    regexp: '127.0.0.1'
    replace: "{{ hostvars[groups['k3s_masters'][0]].internal_ip }}"
  delegate_to: localhost

- name: update cluster name k3s.yaml
  replace:
    path: "{{ kubeconfig }}"
    regexp: 'default'
    replace: "{{ cluster_name }}"
  delegate_to: localhost
```
Excerpt from Ansible k3s-workers role:
```
vars:
  proxy: "http://proxy.ftc5.hpelabs.net:8080"
  no_proxy: "localhost,127.0.0.1,172.20.12.192/26,kightlabs.net,hpelabs.net"

tasks:
---
# tasks file for k3s-workers

- name: get node token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token_result
  become: yes
  delegate_to: "{{ groups['k3s_masters'][0] }}"

- set_fact:
    node_token: "{{ node_token_result.stdout }}"
    master_ip: "{{ hostvars[groups['k3s_masters'][0]].internal_ip }}"

- name: create Downloads directory
  file:
    path: Downloads
    state: directory
    mode: '0755'

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: use_proxy

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  when: not use_proxy

- name: install k3s no proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    INSTALL_K3S_EXEC="--node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    K3S_URL="https://{{ master_ip }}:6443" 
    K3S_TOKEN="{{ node_token }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: not use_proxy
  register: workers_install_result
  become: yes

- name: results of installation
  debug: var=workers_install_result
  when: workers_install_result is changed

- name: install k3s with proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    INSTALL_K3S_EXEC="--node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    K3S_URL="https://{{ master_ip }}:6443" 
    K3S_TOKEN="{{ node_token }}" 
    HTTP_PROXY="{{ proxy }}" 
    HTTPS_PROXY="{{ proxy }}" 
    NO_PROXY="{{ no_proxy }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: use_proxy
  register: workers_install_result
  become: yes

- name: results of installation
  debug: var=workers_install_result
  when: workers_install_result is changed
```
What other info would you like?
