### ISSUE TITLE
Updating Traefik Ingress Configuration 

### ISSUE THREAD

**Issue by mkenne11** [rancher/k3s#1313]
I have K3s (release v1.17.0+k3s.1) installed on my Raspberry Pi cluster, running on Raspbian Buster.

I used the standard configuration for installation, and Traefik is being used as the ingress controller.

I would like to disable TLS verification in Traefik by setting the "insecureSkipVerify" setting to "true".
Note. I am running Kubernetes Dashboard with a self-signed certificate. This is on my home network and I'm not too concerned about verifying the validity of the certificate.

K3s appears to install Traefik using a Helm Chart, and I can see the Traefik chart manifest is installed in:
/var/lib/rancher/k3s/server/manifests/traefik.yaml

I have updated the traefik.yaml in this folder to include the additional setting:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    # New TLS skip verify certificate setting
    ssl.insecureSkipVerify: "true"
```

How can I apply the updated Traefik settings from my chart manifest file?

**Comment by a01fe** [comment]
Make sure your change is still in `traefik.yaml` and re-run the installer adding `--no-deploy=traefik` like this:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy=traefik" sh -
```

**Comment by mkenne11** [comment]
Thanks very much for your assistance @a01fe :) Btw. I installed k3s using the k3sup tool.

I'll try your suggestion and let you know the results. I believe the equivalent command for k3sup is:
```
k3sup install <standard-install-args> --k3s-extra-args '--no-deploy traefik'
```

**Comment by mkenne11** [comment]
Just confirming that both these methods worked to changed the traefik.yaml settings for my k3s install.

**Comment by theAkito** [comment]
Is there no good way of upgrading the `traefik.yaml`? Re-installing the entire k3s application just to apply a new Traefik configuration is at best a workaround.
What is the proper way to update the Traefik configuration?

**Comment by a01fe** [comment]
You need to run the installer once with `--disable traefik` to disable the built-in deployment. After that, all you have to do is change the manifest and `k3s` will reapply it.

**Comment by zhangguanzhang** [comment]
This is too inhumane

**Comment by brandond** [comment]
k3s 1.19 (and current master builds) include a new HelmChartConfig CRD that can be used to customize the values of a HelmChart without modifying the resource itself. The core use case for this is things like the packaged Traefik deployment. See: https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by hwk42** [comment]
the default port 443 was used by other service, for change to another port , I had to reinstall the k3s server ,that is too unpractical.any plan to resolve this?

**Comment by a01fe** [comment]
If you don't want to reinstall, you could edit the service and add `--disable traefik` to the k3s server command line.

**Comment by praveenmak** [comment]
@brandond  one quick question.

When communicating from "traefik <==> backend "  and backend has https on port 22000. 
What is best approach to hit the 22000 (https) port?
I am using
`   
serversTransport:
      insecureSkipVerify = true
`

Is this because of 1.81 (default Traefik version in K3s 1.24) ?
Should I bump up the version of traefik ?

**Comment by brandond** [comment]
I'm not sure what that is for or where you're putting it, but you appear to be mixing yaml and ini style configuration syntax? You don't normally see : and = mixed together.

**Comment by praveenmak** [comment]
We can edit the configMap. 
> k edit cm -n kube-system traefik
Then restart the traefik controller by scaling down and up the pod.

**Comment by davesilva** [comment]
If anyone else is like me and stumbles upon this while trying to figure out how to set `insecureSkipVerify` now that k3s has moved to Traefik v2, here's the easiest way I found to do it:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    globalArguments:
    - "--serversTransport.insecureSkipVerify=true"
```

**Comment by cawoodm** [comment]
> If you don't want to reinstall, you could edit the service and add `--disable traefik` to the k3s server command line.
I'm confused - in order to update the traefik config we have to disable traefik??

**Comment by brandond** [comment]
Yes, you disable it (to uninstall the old traefik v1 chart) and then enable it again to get v2. The v1 chart can't be safely directly upgraded to v2 so you have to basically uninstall and reinstall it.

**Comment by cawoodm** [comment]
OK, the solution with `HelmChartConfig` works nicely. Thanks @davesilva !

I battled with this issue for days now but there was nothing logged to the `kube-system/traefik` pods. They only log some unhelpful deprecation warnings which can't be traced. When I shell into the traefik ingress controller `/var/log` is empty.

Where/how can I see proper traefik error and access logs?

**Comment by brandond** [comment]
You should enable logging in the helm chart values: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L170-L171

**Comment by cawoodm** [comment]
I am unclear as to how this should work. Since we (as users) did not install traefik, I'm not sure how we should manage it via helm. 

The above discussion seems to imply re-installing the k3s server which is a bit extreme. The HelmChartConfig option is nice but I don't see the link to a helm chart or a values.yaml.

**Comment by brandond** [comment]
K3s installs Traefik via helm chat. The values you can set in the HelmChartConfig as shown above are taken directly from the upstream chart values.

**Comment by cawoodm** [comment]
I've read those docs but the various version numbers (helm, traefik, k3s, kubernetes...) are confusing.

Is it:
```yaml
accessLog:
  enabled: true
```
OR
```yaml
logs:
  access:
    enabled: true
```

Where can I see which helm version is employed?

**Comment by cawoodm** [comment]
It seems to be the latter. I am now getting access logs on stdout of the pod.

**Comment by brandond** [comment]
@loganmarchione All that shows is that you've disabled certificate validation on the back-end connection. The error from your unifi web server is that a HTTPS connection between traefik and the pod is required, but you're using HTTP instead. This is not an error about invalid certificates, as you're not even using them.

If you're using an Ingress resource to configure the routing to the pod, you're probably missing something there. See: https://doc.traefik.io/traefik/v2.2/routing/providers/kubernetes-ingress/#on-service

**Comment by loganmarchione** [comment]
@brandond thanks for the quick reply, it's working now!

```
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-service
  namespace: unifi
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8443
      port: 8443
      protocol: TCP
  selector:
    app: unifi
```

**Comment by brandond** [comment]
Note that fixing the port on the service to be properly named `https` instead of incorrectly labeling it as `http` would also have worked, due to traefik being smart enough to guess at protocols based on the port name.

**Comment by loganmarchione** [comment]
> Note that fixing the port on the service to be properly named `https` instead of incorrectly labeling it as `http` would also have worked, due to traefik being smart enough to guess at protocols based on the port name.

Yep you're right, thanks!

**Comment by gavan1** [comment]
@brandond I’m following the k3s.io docs.
When creating the traefik-config.yaml in /var/lib/rancher/k3s/server/manifests/traefik-config.yaml

```
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.8.5
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    ssl:
      enabled: true
      permanentRedirect: false
```

official guide needs to be updated as I get an image pull error and back off.

There must be an overlooked step that is missing from that guide.
