### ISSUE TITLE
nfs mounts do not resolve with coredns

### ISSUE THREAD

**Issue by dlashua** [rancher/k3s#1397]
**Version:**

k3s version v1.17.2+k3s1 (cdab19b0)

curl -sfL https://get.k3s.io | sh -s - server --token xxx --bind-address 192.168.0.4 --advertise-address 192.168.0.4 --node-ip 192.168.0.4 --no-deploy traefik

**Describe the bug**

NFS mounts appear to resolve server names via the node's DNS resolver instead of via coredns.

**To Reproduce**

Create an nfs-server StatefulSet:

```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nfs-maverick
  labels:
    app: nfs-maverick

spec:
  serviceName: nfs-maverick
  replicas: 1
  selector:
    matchLabels:
      app: nfs-maverick
  template:
    metadata:
      labels:
        app: nfs-maverick
    spec:
      containers:
        - name: nfs-maverick
          image: itsthenetwork/nfs-server-alpine
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
            - name: SYNC
              value: "true"
          ports:
            - name: nfs
              containerPort: 2049
          volumeMounts:
            - mountPath: /nfsshare
              name: data
      volumes:
        - name: data
          hostPath:
            path: /mnt/nfs-volumes/
      nodeSelector:
        kubernetes.io/hostname: maverick
```

Create a service for this StatefulSet:
```
apiVersion: v1
kind: Service
metadata:
  name: nfs-maverick
spec:
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
  selector:
    app: nfs-maverick
```

Create a Deployment that attempts to consume this NFS resource:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new
spec:
  selector:
    matchLabels:
      app: nginx-new
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx-new
        image: nginx:1.8
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/test-nfs
          name: nfs-html
      volumes:
      - name: nfs-html
        nfs:
          server: nfs-maverick
          path: /nginx
      nodeSelector:
        kubernetes.io/hostname: maverick
```

**Expected behavior**

Nginx Pod should start without issue.

**Actual behavior**

Nginx Pod remains in "ContainerCreating" status forever. Error logs indicate timeouts attempting to mount NFS share.

Changing the nfs.server parameter to the clusterIP of the service causes it to work.

**Additional context**

I believe that the nfs mount is using the host DNS configuration to resolve the server name instead of coredns.
