### ISSUE TITLE
Error from server (BadRequest): the server rejected our request for an unknown reason

### ISSUE THREAD

**Issue by fooock** [rancher/k3s#1437]
**Version:**
```
# k3s -v
k3s version v1.17.2+k3s1 (cdab19b0)
```

**Describe the bug**
I configured a k3s cluster in HA mode, so to access to the master nodes from my machine, I configured an external Nginx L4 load balancer. The simplified configuration of my nginx configuration is:

```
stream {
  upstream k3s_api {
    server 10.0.0.2:6443;
    server 10.0.0.4:6443;
  }
 server {
    listen 6443;
    proxy_pass k3s_api;
  }
}
```
I copied the kubeconfig file from one of my masters and changed the server URL to point to my external load balancer. Then I checked that kubectl is using the correct context, and executed the following command:

```
$ kubectl get nodes
Error from server (BadRequest): the server rejected our request for an unknown reason
```
Checking the Nginx logs, seems that the response is a 200 code...

```
[2020-02-20T18:44:28+01:00] TCP [200] 76 175 0.002 10.0.0.2:6443 "175" "76" "0.000"
[2020-02-20T18:44:28+01:00] TCP [200] 76 175 0.001 10.0.0.4:6443 "175" "76" "0.000"
[2020-02-20T18:44:28+01:00] TCP [200] 76 175 0.002 10.0.0.2:6443 "175" "76" "0.000"
[2020-02-20T18:44:28+01:00] TCP [200] 76 175 0.002 10.0.0.4:6443 "175" "76" "0.000"
[2020-02-20T18:44:28+01:00] TCP [200] 76 175 0.002 10.0.0.2:6443 "175" "76" "0.000"
```
From the masters node, no log errors.

I expect the list of nodes of the current cluster.

**To Reproduce**
Install a k3s cluster in HA mode with an external load balancer to access masters.

**Expected behavior**
When I execute `kubectl get nodes` from my developer machine, I expect to get the current nodes of my k3s cluster.

**Actual behavior**
I get:
```
$ kubectl get nodes
Error from server (BadRequest): the server rejected our request for an unknown reason
```

**Additional context**

kubectl config view

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: http://XX.XX.XX.XX:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: password
    username: admin
```
kubectl version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Error from server (BadRequest): the server rejected our request for an unknown reason
```

**Comment by fredbeltrao** [comment]
Same problem with **HAProxy** as a **L4 loadbalancer** to **controlplane nodes** in a cluster provisioned by Rancher UI HA Install. (Just for the record: **HAProxy L4 loadbalancer to my ingress nodes is working perfectly**)

kubeconfig file (obtained from Rancher UI):
```
apiVersion: v1
kind: Config
clusters:
- name: "vs-hom"
  cluster:
    server: "https://rancher.tre-pa.jus.br/k8s/clusters/c-4qmjt"
    certificate-authority-data: "LS0tLS1CRUd....DQVRFLS0tLS0="
- name: "vs-hom-fqdn"
  cluster:
    server: "https://k8s-api.tre-pa.jus.br"
    certificate-authority-data: "LS0tLS1CRUd...DQVRFLS0tLS0="

users:
- name: "vs-hom"
  user:
    token: "kubeconfig-user-xr9qr.c-4qmjt:2s7hfs8...km8qkspfnq"

contexts:
- name: "vs-hom"
  context:
    user: "vs-hom"
    cluster: "vs-hom"
- name: "vs-hom-fqdn"
  context:
    user: "vs-hom"
    cluster: "vs-hom-fqdn"

current-context: "vs-hom"
```

`haproxy.cfg`:
```
# _version=11

global 
  daemon
  master-worker
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  # Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private
  # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256

defaults 
  mode tcp
  maxconn 1000
  log global
  option tcplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

userlist dataplane-api 
  user dataplaneapi password my-encrypted-password

frontend k8s-api.tre-pa.jus.br 
  bind *:443 ssl crt /usr/local/share/ca-certificates/k8s-api.tre-pa.jus.br.pem
  default_backend k8s-nodes

backend k8s-nodes 
  balance roundrobin
  option tcp-check
  default-server check weight 100
  server vs-hom-controlplane1 10.13.46.40:6443
  server vs-hom-controlplane2 10.13.46.41:6443
  server vs-hom-controlplane3 10.13.46.42:6443

program api 
  command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist dataplane-api
```

HAProxy logs to confirm that requests are sent to controlplane nodes:
```
Feb 20 18:44:45 lb-k8s-api haproxy[23290]: 10.13.60.111:59152 [20/Feb/2020:18:44:45.109] k8s-api.tre-pa.jus.br~ k8s-nodes/vs-hom-controlplane1 39/0/42 76 -- 1/1/0/0/0 0/0
Feb 20 18:44:45 lb-k8s-api haproxy[23290]: 10.13.60.111:59154 [20/Feb/2020:18:44:45.158] k8s-api.tre-pa.jus.br~ k8s-nodes/vs-hom-controlplane2 38/0/39 76 -- 1/1/0/0/0 0/0
Feb 20 18:44:45 lb-k8s-api haproxy[23290]: 10.13.60.111:59156 [20/Feb/2020:18:44:45.203] k8s-api.tre-pa.jus.br~ k8s-nodes/vs-hom-controlplane3 31/1/32 76 -- 1/1/0/0/0 0/0
Feb 20 18:44:45 lb-k8s-api haproxy[23290]: 10.13.60.111:59160 [20/Feb/2020:18:44:45.243] k8s-api.tre-pa.jus.br~ k8s-nodes/vs-hom-controlplane1 31/1/32 76 -- 1/1/0/0/0 0/0
Feb 20 18:44:45 lb-k8s-api haproxy[23290]: 10.13.60.111:59162 [20/Feb/2020:18:44:45.282] k8s-api.tre-pa.jus.br~ k8s-nodes/vs-hom-controlplane2 31/1/32 76 -- 1/1/0/0/0 0/0

```

Error message when I do `kubectl --user vs-hom --cluster vs-hom-fqdn cluster-info`:
```
fred@rpawssr02:~$ kubectl --user vs-hom --cluster vs-hom-fqdn cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server (BadRequest): the server rejected our request for an unknown reason
```
