### ISSUE TITLE
Custom applied endpoints keeps losing addresses

### ISSUE THREAD

**Issue by NicklasWallgren** [rancher/k3s#1562]
I keep having issues with k3s and custom endpoints, they keep losing their endpoint addresses after awhile. They work great for a few hours, but keeps reverting back to `<none>` after awhile and I have to re-apply the manifests.

I have encountered this issue on different cluster setups.

```
kubectl get endpoints -n=kube-system

kube-controller-manager-prometheus-discovery   <none>                                                          6h23m
kube-scheduler-prometheus-discovery            <none>                                                          6h23m
```

Manifests
```
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-controller-manager-prometheus-discovery
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: <address>
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP

apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-scheduler-prometheus-discovery
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: <address>
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
```

**Comment by carlosedp** [comment]
I’ve seen this after restarting a K3s node too.

**Comment by NicklasWallgren** [comment]
We just updated to the latest stable version of k3s, and we are still seeing this issue.

**Comment by brandond** [comment]
It is my understanding that endpoints are managed by the endpoints controller, which ensures that the addresses for each endpoint are up-to-date and map to the correct pods. If you're manually editing the endpoints, it will periodically validate the configuration and remove your manual changes.

Why are you trying to manually configure endpoints? Is this something that could be accomplished with an ExternalName service?

**Comment by NicklasWallgren** [comment]
Thanks for the reply @brandond

We're currently using https://github.com/carlosedp/cluster-monitoring for monitoring, which is based on https://github.com/prometheus-operator/kube-prometheus. 

As I understand it, k3s doesn't export any endpoints for either the controller manager or scheduler, which is a prerequisite for kube prometheus. In order to get k3s to play nicely with kube prometheus, cluster-monitoring creates services and endpoints which works great, expect that the endpoints keeps losing their addresses.

We're maybe going at it the wrong way. 

@carlosedp Can you provide additional information?

This issue is probably related to https://github.com/rancher/k3s/issues/1244

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
  selector:
    component: kube-scheduler
```

```
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-scheduler-prometheus-discovery
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: <address>
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
```
