### ISSUE TITLE
Add channel support to install script

### ISSUE THREAD

**Issue by erikwilson** [rancher/k3s#1578]
Provide install script support for the k3s channel server.

refs:
https://github.com/rancher/channelserver
http://update.k3s.io/

**Comment by benfairless** [comment]
Hi Erik, quick question. Is the idea here with the channel server so that I can set something like:
```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
...
spec:
  ...
  channel: https://update.k3s.io/v1-release/channels/stable
```

instead of being limited to just tracking latest from GitHub?
