### ISSUE TITLE
Issue using private GCR registry with _json_key

### ISSUE THREAD

**Issue by Dirbaio** [rancher/k3s#1610]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
/usr/local/bin/k3s server --no-deploy traefik --flannel-backend=host-gw --no-deploy servicelb

**Describe the bug**
I am trying to run pods with images from a private GCR registry. The easiest way to do it is to [use a service account key as the password](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key). The issue is that the service account key is a JSON blob, containing quote characters `"`.

**To Reproduce**

- Set this in /etc/rancher/k3s/registries.yaml. (actual key censored)

```
    configs:
      eu.gcr.io:
        auth:
          username: _json_key
          password: '{  "type": "service_account",  "project_id": "XXXX",  "private_key_id": "XXXX",  ...}'
```

- Restart k3s

**Expected behavior**

It works

**Actual behavior**

It doesn't work. containerd crashes because `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` gets generated with the password JSON without quoting:

```
    [plugins.cri.registry.configs."eu.gcr.io".auth]
    username = "_json_key"
    password = "{  "type": "service_account",  "project_id": "xxx",  "private_key_id": "xxx", ... }"
```
