### ISSUE TITLE
Location of flexvolume driver

### ISSUE THREAD

**Issue by nsoubelet** [rancher/k3s#1631]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
--flannel-iface XX  \
 --no-deploy=traefik \
 -i YY \
 --node-external-ip YY \
 --cluster-domain ZZ

**Issue:**
After installing Azure SMB Flexvolume driver, I found that the standard location of the driver in a regular k8s setup is `/etc/kubernetes/volumeplugins`, in fact, driver is installed in `/etc/kubernetes/volumeplugins/microsoft.com~smb/smb`

Installation script https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/smb/deployment/install-smb-flexvol-ubuntu.sh

**Information needed:**
However, since when trying to use a volume in a Pod I get the following `flexvolume error err=no volume plugin matched` I presume that the driver is not properly located so I would like to know where to _manually_ place drivers in k3s so kubelet is able to properly pick them up after restart.

**Comment by nsoubelet** [comment]
Just to add more info, I just found to that the default location where kubelet goes for loading volume drivers is `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/` unless one specify a different one via `--kubelet-arg` flag as specified in https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/.

I tried copying smb driver using both approaches but still getting the message `failed to get Plugin from volumeSpec for volume "pv-smb-flexvol" err=no volume plugin matched`

**Pod manifest:**
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-smb
spec:
  containers:
  - name: nginx-flex-smb
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "microsoft.com/smb"
      secretRef:
        name: smbcreds	
      options:
        source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
        mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777"
```

I would appreciate if someone can share similar issues/experience dealing with drivers in general and flexvolume in particular in k3s.

Thanks

**Comment by brandond** [comment]
You might see if you have more luck with the CSI driver, since that's where things are going.

https://github.com/kubernetes-sigs/azurefile-csi-driver

**Comment by nsoubelet** [comment]
Hi @brandond 
Yes, I noticed k8s's storage is in general moving towards that direction, however my perception is that csi drivers are not yet as stable/tested as one can expect, including azure's.

I will give a try and will let you know.

**Comment by brandond** [comment]
I've never used FlexVolume, only CSI, but from the FlexVolume docs:

```To install the FlexVolume driver, place the executable file at the volume plug-in path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/<vendor>~<driver>/<driver>. For example, to install the FlexVolume driver for the storage foo, place the executable file at: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/openshift.com~foo/foo.```

So, it looks like you want to set your driver to "smb" instead of "microsoft.com/smb"

**Comment by nsoubelet** [comment]
As per described in the text you posted, my understanding is that the folowing:
 ```
 volumes:
  - name: test
    flexVolume:
      driver: "microsoft.com/smb"
```
Needs a driver, located in `[kubelet-vol-drivers-dir]/microsoft.com~smb` with the actual script inside. That is exactly what I have and yet not working.
