### ISSUE TITLE
Exposing service via kubectl vs exposing service via deployment file

### ISSUE THREAD

**Issue by diggnsaegg** [rancher/k3s#1689]
Hey there,

I am playing around with k3s alot and I am not able to expose a service on Port 80 (because traefik uses this port) via a deployment file. But exposing via kubectl works like a charm. Where is the difference though? The resource type is the same and the output of kubectl get service myservice also.

But take a look: 

My Deployment:

`apiVersion: v1
kind: Service
metadata:
  name: bla
spec:
  type: LoadBalancer
  selector:
    component: bla
  ports:
    - port: 80
      targetPort: 80`

This creates this output:

`bla     LoadBalancer   10.43.175.24    192.168.178.151     80:32004/TCP   3s`

When I try to access the service it redirects me to port 80 and a 404 (this is traefik I guess).

This works:

`kubectl expose deployment mydeployment --type=LoadBalancer --name=bla --external-ip=192.168.178.151 --port=80
`

The output from "kubectl get service" looks the same, but I dont get why it doesn't work via my deployment file? Do I miss something here ? How do I address traefik in my deployment file to manage that service for me like it does with kubectl expose command?

Thanks

Dan

**Comment by a01fe** [comment]
You might want to read https://kubernetes.io/docs/concepts/services-networking/service/ for documentation on services and ingresses.

To use Traefik, you should use a `ClusterIP` service like this:

```
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - name: web
    port: 80
    targetPort: 80
```

The selector is important, it's what ties the service to pods in your deployment.

Then create an Ingress like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp-service
          servicePort: web
```
