### ISSUE TITLE
Insecure Private Registry Configuration: Server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by danlister** [rancher/k3s#1713]
I have been following https://rancher.com/docs/k3s/latest/en/installation/private-registry/ to setup a local insecure registry at `http://registry.local:5000/`. 

The registry is running as a docker container. I can successfully navigate to the registry from both master and worker nodes. For example, `http://registry.local:5000/v2/_catalog` returns the below. I have also verified the correct image version exists within the registry.

```
{"repositories":[agebase/raspberrypiandk3sdemo]}
```

I have added the following config to `/etc/rancher/k3s/registries.yaml`:

```
mirrors:
  docker.io:
    endpoint:
      - "http://registry.local:5000"
```

I can verify the mirror when running `crictl info` on any of the nodes:

```
"registry": {
  "mirrors": {
    "docker.io": {
      "endpoint": [
         "http://registry.local:5000"
      ]
    }
  },
  "configs": null,
  "auths": null 
}
```

Given the following manifest...

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspberry-pi-and-k3s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raspberry-pi-and-k3s-demo
  template:
    metadata:
      labels:
        app: raspberry-pi-and-k3s-demo
    spec:
      containers:
      - name: raspberry-pi-and-k3s-demo
        image: registry.local:5000/agebase/raspberrypiandk3sdemo:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: raspberry-pi-and-k3s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: raspberry-pi-and-k3s-demo
```

... when applying the manifest, the image fails to pull. I receive an `ErrImagePull` message on the pod. When looking deeper, I can see the following error message:

```
failed to do request: Head https://registry.local:5000/v2/agebase/raspberrypiandk3sdemo/manifests/1.0.0: http: server gave HTTP response to HTTPS client
```

Any help would be greatly appreciated please
