### ISSUE TITLE
fileBackend option does not work in traefik helm chart

### ISSUE THREAD

**Issue by rogeliodh** [rancher/k3s#1790]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
curl -sfL https://get.k3s.io | sh -

**Describe the bug**
Edited /var/lib/rancher/k3s/server/manifests/traefik.yaml
to add fileBackend field:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system      
spec:  
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz                                                                                 
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"                                                                                                                                
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    image: "rancher/library-traefik"
    fileBackend: |
      [backends]
        [backends.backend1]
```
The contents are just a test to see if it works (but valid toml)

But it fails to reload with this log:

```
CHART=$(sed -e "s/%{KUBERNETES_API}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/g" <<< "${CHART}")
set +v -x
+ cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/        
+ update-ca-certificates                                                                             
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping     
+ + export HELM_HOST=127.0.0.1:44134
tiller --listen=127.0.0.1:44134 --storage=secret          
+ HELM_HOST=127.0.0.1:44134                    
+ helm_v2 init --skip-refresh --client-only
[main] 2020/05/13 00:25:45 Starting Tiller v2.12.3 (tls=false)
[main] 2020/05/13 00:25:45 GRPC listening on 127.0.0.1:44134
[main] 2020/05/13 00:25:45 Probes listening on :44135
[main] 2020/05/13 00:25:45 Storage driver is Secret
[main] 2020/05/13 00:25:45 Max history per release is 0
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache    
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts                                     
$HELM_HOME has been configured at /root/.helm.             
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
++ helm_v2 ls --all '^traefik$' --output json                
++ jq -r '.Releases | length'
[storage] 2020/05/13 00:25:45 listing all releases with filter
+ EXIST=
+ '[' '' == 1 ']'
+ '[' '' == v2 ']'
+ helm_repo_init
+ grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
chart path is a url, skipping repo update
+ helm_v3 repo remove stable   
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string 'fileBackend=[backends]' '[backends.backend1]' --set-string image=rancher/library-traefik --set kubernetes.ingressEndpoint.useDefaultPublishedService=true --set metrics.prometheus.enabled=true --set rbac.enabled=true --set ssl.enabled=true
+ '[' helm_v3 == helm_v3 ']'
++ tr '[:upper:]' '[:lower:]'                                                                                                                      
++ helm_v3 ls --all -f '^traefik$' --output json                             
++ jq -r '"\(.[0].app_version),\(.[0].status)"'    
+ LINE=1.7.19,deployed
++ echo 1.7.19,deployed
++ cut -f1 -d,                                                                                                                                     
+ INSTALLED_VERSION=1.7.19
++ echo 1.7.19,deployed
++ cut -f2 -d,
+ STATUS=deployed
+ '[' -e /config/values.yaml ']'
+ '[' install = delete ']'
+ '[' -z 1.7.19 ']'
+ '[' -z '' ']'
+ '[' deployed = deployed ']'                                                                                                                      
+ echo Already installed traefik, upgrading
Already installed traefik, upgrading
+ shift 1
+ helm_v3 --set-string 'fileBackend=[backends]' '[backends.backend1]' --set-string image=rancher/library-traefik --set kubernetes.ingressEndpoint.useDefaultPublishedService=true --set metrics.prometheus.enabled=true --set rbac.enabled=true --set ssl.enabled=true upgrade traefik https://10.43.0.1:443/static/charts/traefik-1.81.0.tgz             
Error: unknown flag: --set-string
```

**Expected behavior**
Install ok

**Actual behavior**
Installation fails

**Additional context / logs**
I tried with a single string and it works:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system                                                                                                                           spec:  
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz                                                                                 
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"                                                                                                                                
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    image: "rancher/library-traefik"
    fileBackend: "[backends]"
```
and it works, so it seems it is a problem with multiline fields.

**Comment by tpihl** [comment]
This is unfortunalty a dealbreaker for us, so i guess "kubeadm, here we come"

**Comment by brandond** [comment]
Take a look at how your multiline string gets rendered into the command-line:

```
helm_v3 --set-string 'fileBackend=[backends]' '[backends.backend1]' --set-string image=rancher/library-traefik --set kubernetes.ingressEndpoint.useDefaultPublishedService=true --set metrics.prometheus.enabled=true --set rbac.enabled=true --set ssl.enabled=true upgrade traefik https://10.43.0.1:443/static/charts/traefik-1.81.0.tgz             
```

The `--set-string 'fileBackend=[backends]' '[backends.backend1]'` bit isn't valid. `--set-string` consumes a single following `key=value` argument, but in this case is given two, which breaks parsing of the remaining arguments.

Since everything is run through bash, I found that it was actually surprisingly difficult to pass a newline into the argument. Here's what finally worked for me:
`--set-string $'fileBackend=  [backends]\n    [backends.backend1]'`

That said, I'm not sure how to get the helm script to output something like this in response to a multiline value...

**Comment by brandond** [comment]
This is a limitation of of the helm `-set`,`--set-string`, etc options. For more complicated stuff where you need to pass through a list, map, multiline string, etc it's better to use valuesContent. I just put in a docs PR that will hopefully make this a more obvious solution.

For the given issue, my suggestion would be to do something like this:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system      
spec:  
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz                                                                                 
  valuesContent: |
    rbac:
      enabled: true
    ssl:
      enabled: true                                                                                                                                
    metrics:
      prometheus:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    image: rancher/library-traefik
    fileBackend: |
      [backends]
        [backends.backend1]
```
