### ISSUE TITLE
KubeRouter: implement External Load Balancer backed by External BGP Peers

### ISSUE THREAD

**Issue by blaggacao** [rancher/k3s#1813]
**Is your feature request related to a problem? Please describe.**
For enabling ExternalLoadBalancer, my only HA option is using MetalLB. This is against the core philosophy of k3s of being tiny and feature complete.

Although [this comment](https://github.com/rancher/k3s/issues/77#issuecomment-482251287) expresses concern of not changing the k8s behavior, this is too much of a convenience win if it could be made optional.

**Describe the solution you'd like**
Behind supported router hardware, it should just advertise External Service IPs through [Global External BGP Peers](https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md#global-external-bgp-peers) or [Node Specific External BGP Peers](https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md#node-specific-external-bgp-peers) for rack and spine setups. 

Additional suggestion: extend the [kubernetes well known labels](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/) of:
```yaml
    topology.kubernetes.io/region: bogota
    topology.kubernetes.io/zone: office-cedritos
    # edge bgp-extension
    topology.kubernetes.io/spine: floor5
    topology.kubernetes.io/rack: goblin
```

**Describe alternatives you've considered**
Bundle MetalLB, for support of L2 mode, but eventually that's less aligned with the single binary single process approach than what kube-router has to offer.

L2 **could** be implemented apart or over kube-router.

**Additional context**
[Big boss has spoken](https://www.youtube.com/watch?time_continue=2004&v=-HchRyqNtkU&feature=emb_logo) :wink:  - especially at [29:32](https://youtu.be/-HchRyqNtkU?t=1772) - do it and replace this thing at [28:05](https://youtu.be/-HchRyqNtkU?t=1685)

/cc @ibuildthecloud 

Would superseed #366 (slightly paraphrasing it's motivation)
