### ISSUE TITLE
Failed to find memory cgroup (Only in nodes, not in masters)

### ISSUE THREAD

**Issue by DrumSergio** [rancher/k3s#1825]
**Version:** 
(In all of my 7 nodes)
```
v1.18.2+k3s1 (698e444a)
```

**K3s arguments:**
This is part of the playbook I use to kick up my cluster, although the problem persists even when I try to install it manually:
```
- hosts: master1
  become: yes
  tasks:
  - name: Install K3s in master
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_EXEC: " --no-deploy servicelb --no-deploy traefik --cluster-init"
      K3S_TOKEN: "notforshare"

  - name: Read node-token from master
    slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: node_token

  - name: Store Master node-token
    set_fact:
      token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- hosts: master2:master3
  become: yes
  tasks:
  - name: Install K3s in the rest of the masters
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_EXEC: " --server https://192.168.0.100:6443"
      K3S_TOKEN: "notforshare"

- hosts: nodes
  become: yes
  tasks:
  - name: Install K3s in nodes
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      K3S_URL: "https://192.168.0.100:6443"
      K3S_TOKEN: "{{ hostvars[groups['masters'][0]]['token'] }}"
``` 

**Describe the bug**
I have 3 masters: master1 is a Pi 4-4GB, and master2 and master3, a Pi 4-2GB.
I have 4 worker nodes: node1 and node2 are a Pi 3B+ and node3 and node4 are a Pi 3B.
It sucessfully installs everywhere, but when I perform a `journalctl -xe` this is the output of every worker node:
```
level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
```
This is a strange behaviour, everything is perfect inside `cmdline.txt`, in fact my Ansible playbook makes the same action whether it is on masters or nodes, and I can't replicate the error on masters. I have tried modifying the order in `cmdline.txt` without success. I can check that this is working as expected because I can see it in the output when I issue a `cat /proc/cmdline`.

**To Reproduce**
Install a worker node on a 3B/3B+ Pi with the Linux kernel 5.4.42-v7+

**Additional logs**
Agent service status:
```
pi@K3sNode1:~ $ sudo service k3s-agent status
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-05-25 14:40:20 CEST; 4s ago
     Docs: https://k3s.io
  Process: 28346 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 28347 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 28348 ExecStart=/usr/local/bin/k3s agent (code=exited, status=1/FAILURE)
```
k3s-agent.service file, permissions `-rw-r--r-- 1 root root`:
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=exec
EnvironmentFile=/etc/systemd/system/k3s-agent.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    agent \
```
k3s-agent.service.env file, permissions `-r-------- 1 root root`:
```
K3S_KUBECONFIG_MODE=644
K3S_TOKEN=blahblahblah1::server:blahblahblah2
K3S_URL=https://192.168.0.100:6443
```
