### ISSUE TITLE
Traefik redirects ingress to https automatically

### ISSUE THREAD

**Issue by c0dyhi11** [rancher/k3s#1828]
**Version:**
k3s version v1.18.2+k3s1 (698e444a)

**K3s arguments:**
N/A - *Generic install*

**Describe the bug**
Hello, I'm not sure if this is a traefik issue or a k3s issue. But I can't find where this redirect is happening. 
I've created a very generic ingress rule:
```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-first-ingress
spec:
  rules:
  - host: k3s.codyhill.dev
    http:
      paths:
      - path: /my-first-app
        backend:
          serviceName: my-first-app
          servicePort: 80
```

And when I connect to the URL: http://k3s.codyhill.dev/my-first-app via Firefox, Chrome, or Safari... I get automatically redirected to https where the ssl cert has expired and I can't even accept the risk to bypass this...

But if I connect via curl:
```bash
curl http://k3s.codyhill.dev/my-first-app
```
The webpage loads as expected.

**To Reproduce**
Install generic k3s and install a generic app and service:
```bash
curl -sfL https://get.k3s.io
sleep 30
kubectl apply -f https://raw.githubusercontent.com/packet-labs/k8s-videos/master/configmaps/my-first-app-configmap.yaml
kubectl apply -f https://raw.githubusercontent.com/packet-labs/k8s-videos/master/configmaps/deployment-with-configmap.yaml
```
Apply the ingress rule shown above.
Now test to see what happens.

**Expected behavior**
I would expect this to just display my webpage on port 80 without a redirect.

**Actual behavior**
Unless you use `curl` you get redirected to https and that cert isn't valid.

**Additional context / logs**
My goal is to build some videos using k3s and how to basic things with kubernetes. I'd like to show folks how to do basic ingress. And the next video will be securing this with cert-manager. But I can't get a basic ingress rule to work with k3s/traefik.
