### ISSUE TITLE
ServiceLB not detecting removed loadbalancers

### ISSUE THREAD

**Issue by ShadowJonathan** [rancher/k3s#1870]
(Re-issuing of https://github.com/rancher/klipper-lb/issues/3, because i've possibly posted that in the wrong spot after seeing what `ServiceLB` does)

**Version:**
`k3s version v1.17.5+k3s1 (58ebdb2a)`

**K3s arguments:**
*k3os installation, default arguments, no tampering*

`k3os version v0.10.1`

**Describe the bug**

Editing a `Service` resource to no longer have a `LoadBalancer` as it's type, or removing it, does not get detected, and daemonset pods + iptable rules will not be removed.

When a `ServiceLB` daemonset gets removed, the corresponding iptables aren't flushed/removed.

**To Reproduce**

1: Install a clean k3os instance.
2: Add a pod resource that opens a port
3: Add a `LoadBalancer`-typed resource
4: Confirm that daemonset pod gets created.
5: Remove pod and service
6: Observe stale daemonset and iptables

**Expected behavior**

For the daemonset to be removed and the iptables to be cleared of corresponding rules.

**Actual behavior**

Daemonset stays up despite missing container, iptables rules are stale.

**Comment by brandond** [comment]
Are you sure your change is valid? There are a number of gotchas when changing service types, as some keys are or are not allowed to be set in combination with particular service types, and this will cause the update to be rejected. Can you confirm that cluster has actually accepted the service spec update?

**Comment by ShadowJonathan** [comment]
In this particular case I can remember changing `LoadBalancer` to `ClusterIP`, and then having to remove the `nodePort` (yes, it was in there) to allow the change.

I don't know if that particular bug or situation triggered this bug, but it was produced by using the `k8s-land/gitea` chart with nodePort on the service.gitea path.

**Comment by rancher-max** [comment]
- With the exact steps of "removing the pod and service" as mentioned it is deleting the daemonset for me in my tests.
- **However**, it appears the service is actually being edited to be ClusterIP instead of LoadBalancer?
In this case I can confirm the daemonset erroneously remains. 

I was deploying the following yaml for simple testing, and then editing service type to `ClusterIP` and removing the `nodePort` value from the spec directly with `kubectl edit`:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
               protocol: TCP
```

- If deploying ONLY a service with type LoadBalancer, it also creates the daemonset. I believe this would be expected behavior, even though it is somewhat invalid of a scenario. 
- If deploying the above yaml with type set as `ClusterIP` originally, then a daemonset is never deployed with it.
