### ISSUE TITLE
hostPort and hostIP config fails to create iptables rules/chains

### ISSUE THREAD

**Issue by rolinux** [rancher/k3s#1889]
**Version:**
k3s version v1.18.3+k3s1 (96653e8d) running on Ubuntu 20.04 (master and target agents are AMD64 and there is also a ARM64 agent but unused for this deployment)

**K3s arguments:**
export INSTALL_K3S_EXEC='server --tls-san 192.168.7.5' so using default containerd and not docker.

**Describe the bug**
Deployed unifi-video-controller and tried to map 2 ports to the secondary network of an agent. The pod is deployed but I cannot see any KUBE-HOSTPORTS or KUBE-HP- prefix iptables chains on the agent (as of https://github.com/rancher/k3s/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport.go)

I can telnet to the port 6666 probably because the agent opens that port to keep it busy but I don't think the traffic is forwarded to the pod.

I only have the following rules related to KUBE:
```
root@nuc6:/var/log# iptables --list-rules | grep KUBE
-N KUBE-EXTERNAL-SERVICES
-N KUBE-FIREWALL
-N KUBE-FORWARD
-N KUBE-KUBELET-CANARY
-N KUBE-PROXY-CANARY
-N KUBE-SERVICES
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

**To Reproduce**
The deployment YAML includes the following ports setup and even with or without hostIP the hostPort doesn't work:

```
          ports:
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: inbound
              containerPort: 6666
              protocol: TCP
              hostPort: 6666
              #hostIP: 192.168.3.9
            - name: talkback
              containerPort: 7004
              protocol: UDP
            - name: http
              containerPort: 7080
              protocol: TCP
            - name: management
              containerPort: 7442
              protocol: TCP
              hostPort: 7442
              #hostIP: 192.168.3.9
            - name: https
              containerPort: 7443
              protocol: TCP
            - name: rtmps
              containerPort: 7444
              protocol: TCP
            - name: httpvideo
              containerPort: 7445
              protocol: TCP
            - name: httpsvideo
              containerPort: 7446
              protocol: TCP
            - name: rtsp
              containerPort: 7447
              protocol: TCP
```

The container is privileged:

```
      containers:
        - name: controller
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
``` 
**Expected behavior**
Traffic to be forwarded from cameras towards the pod.

**Actual behavior**
No traffic is forwarded from cameras towards the pod, I have not tried to use tcpdump but I reckon the missing iptables chains should be enough.

**Additional context / logs**
