### ISSUE TITLE
Local-path not working air-gap, missing busybox

### ISSUE THREAD

**Issue by bflorat** [rancher/k3s#1908]
**Version:**
v1.17.5+k3s1 (58ebdb2a)

**Describe the bug**
Local-path  can't create PV (can't create the provisionner containers) because busybox image (default image) is missing from air-gap images tarball. 

Workaround : in `/var/lib/rancher/k3s/server/manifests/local-storage.yaml`, force an available image
using `--helper-image` option : 

```

apiVersion: apps/v1
kind: Deployment
metadata:
name: local-path-provisioner
namespace: kube-system
spec:
replicas: 1
selector:
matchLabels:
app: local-path-provisioner
template:
metadata:
labels:
app: local-path-provisioner
spec:
serviceAccountName: local-path-provisioner-service-account
containers:
- name: local-path-provisioner
image: rancher/local-path-provisioner:v0.0.11
imagePullPolicy: IfNotPresent
command:
- local-path-provisioner
- start
- --config
- /etc/config/config.json
- --helper-image
- <an available image>
```
However, this file is overridden at each cluster restarts (no idea why, I'm going to create another ticket for this)

**Comment by samirsss** [comment]
We had a similar issue and added busy box to the set of pods that we were tarring up for offline installation. This actually helped up to leverage busybox for a few init container images rather than using larger containers.

**Comment by brandond** [comment]
We really should be mirroring the busybox image, in addition to preloading it in the airgap image list. I've opened an issue upstream to track: https://github.com/rancher/local-path-provisioner/issues/120

**Comment by rancher-max** [comment]
#### Validated in `v1.19.1-rc2+k3s1`

- `rancher/library-busybox:1.31.1` is present in both arm and amd setups, and uses the correct architecture.
- RIght now this is actually present in `local-storage.yaml` as a helper image:
```
spec:
      serviceAccountName: local-path-provisioner-service-account
      tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.14
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - start
        - --config
        - /etc/config/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HELPER_IMAGE
          value: rancher/library-busybox:1.31.1
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
...
```
- Following the [main instructions](https://github.com/rancher/local-path-provisioner#usage) from using local-path-provisioner, validated it could be used successfully:  -- note that there are a few more steps involved, either image mirroring or supplying a compressed image tar to k3s, to get the `nginx:stable-alpine` that is used by the pod.yaml there
