### ISSUE TITLE
Starting k3s failed on v1.18.4

### ISSUE THREAD

**Issue by DrumSergio** [rancher/k3s#1948]
**Version:**
k3s version v1.18.4+k3s1 (97b7a0e9)

**K3s arguments:**
INSTALL_K3S_EXEC: " --disable servicelb --disable traefik --cluster-init"

**Describe the bug**
The systemd process exits without more info

**To Reproduce**
Just install v1.18.4 on a RPi multi-master cluster. Latest stable Raspbian. Using a RPi 4B with 4GB of RAM as a master.

**Expected behavior**
To continue running

**Actual behavior**
The process exits

**Additional context / logs**
```
Jun 23 22:18:59 master1 systemd[1]: Starting Lightweight Kubernetes...
Jun 23 22:19:00 master1 k3s[749]: time="2020-06-23T22:19:00.267424119+02:00" level=info msg="Starting k3s v1.18.3+k3s1 (96653e8d)"
Jun 23 22:19:14 master1 systemd[1]: k3s.service: Main process exited, code=killed, status=11/SEGV
Jun 23 22:19:14 master1 systemd[1]: k3s.service: Failed with result 'signal'.
Jun 23 22:19:14 master1 systemd[1]: Failed to start Lightweight Kubernetes.
Jun 23 22:19:19 master1 systemd[1]: k3s.service: Service RestartSec=5s expired, scheduling restart.
Jun 23 22:19:19 master1 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 10.
Jun 23 22:19:19 master1 systemd[1]: Stopped Lightweight Kubernetes.
```

```
-- The job identifier is 181500 and the job result is done.
Jun 24 13:40:07 master1 systemd[1]: Starting Lightweight Kubernetes...
-- Subject: A start job for unit k3s.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit k3s.service has begun execution.
-- 
-- The job identifier is 181500.
Jun 24 13:40:07 master1 k3s[25077]: time="2020-06-24T13:40:07.726674695+02:00" level=info msg="Starting k3s v1.18.4+k3s1 (97b7a0e9)"
Jun 24 13:40:19 master1 systemd[1]: k3s.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit k3s.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 11.
Jun 24 13:40:19 master1 systemd[1]: k3s.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit k3s.service has entered the 'failed' state with result 'signal'.
Jun 24 13:40:19 master1 systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: A start job for unit k3s.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit k3s.service has finished with a failure.
-- 
-- The job identifier is 181500 and the job result is failed.
Jun 24 13:40:25 master1 systemd[1]: k3s.service: Service RestartSec=5s expired, scheduling restart.
Jun 24 13:40:25 master1 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 2.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Automatic restarting of the unit k3s.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jun 24 13:40:25 master1 systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: A stop job for unit k3s.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit k3s.service has finished.

```

**Comment by brandond** [comment]
It's crashing with a segfault which is unusual. Is this 32bit or 64bit Raspbian? Which Raspbian release?

**Comment by DrumSergio** [comment]
Raspbian Buster, release 13/02/13, 32-bit

**Comment by brandond** [comment]
What is 13/02/13? The current release is 2020-05-27, and Buster didn't exist in 2013 - they were still on wheezy at the time I believe.

**Comment by davidnuzik** [comment]
Hello, just chiming in. I tested and was unable to reproduce. This may not help with identifying the issue, but I just wanted to post my results. Please let me know if I should try anything else in my environment.

**Environment:**
Single-node cluster, one RasPi 4 4GB

```
pi@davidspi4:~ $ uname -a
Linux davidspi4 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```

```
pi@davidspi4:~ $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**How k3s was installed:**
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable servicelb --disable traefik --cluster-init" sh -
```

**Checks:**

```
pi@davidspi4:~ $ sudo k3s kubectl get nodes
NAME        STATUS   ROLES    AGE   VERSION
davidspi4   Ready    master   11m   v1.18.4+k3s1
```

```
pi@davidspi4:~ $ sudo k3s kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   metrics-server-7566d596c8-dkntw          1/1     Running   0          6m22s
kube-system   local-path-provisioner-6d59f47c7-knfcr   1/1     Running   0          6m22s
kube-system   coredns-8655855d6-tkx46                  1/1     Running   0          6m22s
```

**Detail:**

Nothing unusual in systemd logs (`journalctl -u k3s`)

**Comment by DrumSergio** [comment]
Reinstalled everything again and same problem. Any clue on how to diagnose? I install my local cluster with Ansible, there you have the 2 yaml's:

prepare_raspbian.yaml
```
---

- hosts: pis
  become: yes
  tasks:
  - name: Update and upgrade system
    apt:
      autoremove: yes
      update_cache: yes
      upgrade: dist

  - name: Disable swap on Raspbian
    apt:
      name: dphys-swapfile
      state: absent
      purge: yes

  - name: Install NFS utilities
    apt:
      name: nfs-common
      state: present

  - name: Add mount
    lineinfile:
      path: /etc/fstab
      regexp: "^192"
      line: "192.168.0.5:/Multimedia/K3s_persistent   /mnt/persistent   nfs    rw  0  0"
      state: present
      insertafter: EOF

  - name: Set Timezone
    timezone:
      name: Europe/Madrid

  - name: Configure GPUmem to 16
    lineinfile:
      path: /boot/config.txt
      regexp: "^#?gpu_mem"
      line: "gpu_mem=16"
      insertafter: EOF
      state: present

  - name: Disable HDMI
    lineinfile:
      dest: /etc/rc.local
      regexp: "^/usr/bin/tvservice"
      line: "/usr/bin/tvservice -o"
      insertbefore: "^exit"
      state: present

  - name: Set password
    user:
      name: pi
      password: $6$mysecretsalt$XWy9Io/.xC5MGu5Rq4BDoY.BKv3.knqqSCPUXKU7r0/c/iVh1dfnfsD5vnPlt9/GALIhepbn1rgCJQxNECds40

  - name: Enable container features
    replace:
      path: /boot/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
    with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"

  - name: Ensure GB-UTF8 locale exists
    locale_gen:
      name: en_GB.UTF-8
      state: present

  - name: Set firewall to legacy iptables
    command: update-alternatives --set iptables /usr/sbin/iptables-legacy
    command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

  - name: Restart to finalize the changes
    reboot:
      reboot_timeout: 60
      post_reboot_delay: 15

```

install_k3s.yaml
```
- hosts: master1
  become: yes
  tasks:
  - name: Install K3s in master
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_EXEC: " --disable servicelb --disable traefik --cluster-init"
      K3S_TOKEN: "hb7g89453thnj5io42n9y2890omthd5o2klfm39t0v54mnjgvkl54"

  - name: Read node-token from master
    slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: node_token

  - name: Store Master node-token
    set_fact:
      token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

  - name: Copy Kubeconfig to local
    fetch:
      dest: /home/geiser/.kube/config/k3s.yaml
      src: /etc/rancher/k3s/k3s.yaml
      flat: yes

  - name: Kubectl autocompletion #1
    lineinfile:
      path: /home/pi/.bashrc
      regexp: "{{ item.regexp }}"
      insertafter: EOF
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^source ', line: 'source <(kubectl completion bash)' }
      - { regexp: '^alias k=', line: 'alias k=kubectl' }
      - { regexp: '^complete ', line: 'complete -F __start_kubectl k' }

  - name: Kubectl autocompletion #2
    shell: 'kubectl completion bash >/etc/bash_completion.d/kubectl'

  - name: Wait to completely load K3s
    wait_for:
      timeout: 20

- hosts: master2:master3
  become: yes
  tasks:
  - name: Install K3s in the rest of the masters
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_EXEC: "  --disable servicelb --disable traefik --server https://192.168.0.100:6443"
      K3S_TOKEN: "hb7g89453thnj5io42n9y2890omthd5o2klfm39t0v54mnjgvkl54"

- hosts: nodes
  become: yes
  tasks:
  - name: Install K3s in nodes
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      K3S_URL: "https://192.168.0.100:6443"
      K3S_TOKEN: "{{ hostvars[groups['masters'][0]]['token'] }}"

```
