### ISSUE TITLE
Loading Helm manifests without namespace or default fails

### ISSUE THREAD

**Issue by erikwilson** [rancher/k3s#196]
From rancher/k3s/issues/151

> As for helm charts, I tried:
> 
> ```
> apiVersion: k3s.cattle.io/v1
> kind: HelmChart
> metadata:
>   name: redis
> spec:
>   chart: stable/redis
> ```
> which doesn't work for me. I don't get any error output about it either. This doesn't either:
> 
> ```
> apiVersion: k3s.cattle.io/v1
> kind: HelmChart
> metadata:
>   name: redis
>   namespace: default
> spec:
>   chart: stable/redis
> ```
> Only specifiying kube-system seems to work:
> 
> ```
> apiVersion: k3s.cattle.io/v1
> kind: HelmChart
> metadata:
>   name: redis
>   namespace: kube-system
> spec:
>   chart: stable/redis
> ```
> Editing this chart to say `default` results in it creating `job.batch/helm-delete-redis` to delete redis from cluster.

**Comment by epicfilemcnulty** [comment]
@dpen2000 it's just not clear from the docs, but the namespace in `metadata` section is the namespace for the HelmChart CRD resource, so it's probably best to leave `kube-system` there. The actual namespace where all helm chart resources will reside is set with `targetNamespace`:

```
apiVersion: k3s.cattle.io/v1                                                                                                                                                
kind: HelmChart                                                                                                                                                             
metadata:
  name: rook-operator
  namespace: kube-system
spec:
  chart: rook-ceph
  repo: https://charts.rook.io/stable
  targetNamespace: rook-ceph-system
  valuesContent: |-
    agent:
      flexVolumeDirPath: "/var/lib/kubelet/volume-plugins"
```
