### ISSUE TITLE
ServiceLB has inconsistent behaviour with externalTrafficPolicy

### ISSUE THREAD

**Issue by predakanga** [rancher/k3s#1982]
**Environmental Info:**
K3s Version:
v1.18.4+k3s1

Node(s) CPU architecture, OS, and Version:
Ubuntu 20.04 (linux 5.4.0-39-generic, x86_64)

Cluster Configuration:
Masters: 1 (sqlite)
Workers: 1
Networking: Flannel w/ IPSec backend
Traefik disabled
Feature gates enabled: ConfigurableFSGroupPolicy, EndpointSlice, ServiceTopology

**Describe the bug:**
Ingress traffic through a ServiceLB LoadBalancer does not get routed as expected according to k8s docs. Additionally, the behaviour changes depending on the "EXTERNAL-IP" of the Service.

**Steps To Reproduce:**
- Installed K3s on the master: `curl -sfL https://get.k3s.io | sh -s - --disable traefik --flannel-backend ipsec --node-label topology.kubernetes.io/region=a --node-label topology.kubernetes.io/zone=x --kubelet-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-apiserver-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-scheduler-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-controller-manager-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-cloud-controller-manager-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-proxy-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true"`
- Installed K3s on the worker: `curl -sfL https://get.k3s.io | K3S_URL="..." K3S_TOKEN="..." sh -s - --node-label topology.kubernetes.io/region=a --node-label topology.kubernetes.io/zone=x --kubelet-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true" --kube-proxy-arg "feature-gates=ConfigurableFSGroupPolicy=true,EndpointSlice=true,ServiceTopology=true"`
- Create a netcat server pod and a LoadBalancer exposing it
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: echo
  name: echo
spec:
  containers:
  - image: subfuzion/netcat
    name: echo
    args:
    - "-vkl"
    - "9210"
    ports:
    - containerPort: 9210
---
apiVersion: v1
kind: Service
metadata:
  name: echo-local
spec:
  ports:
  - port: 9210
    targetPort: 9210
  selector:
    app.kubernetes.io/name: echo
  externalTrafficPolicy: Local
  type: LoadBalancer
```
- From outside the cluster, connect to the service (`nc -v node-ip 9210`)
- Check the pod's logs to verify the source IP
- Repeat with externalTrafficPolicy: Cluster

**Expected behavior:**
When externalTrafficPolicy is Local, traffic should only be routed to pods on the node you connect to, and source IP addresses should be preserved.
When externalTrafficPolicy is Cluster, traffic should be routed to pods on all nodes, and source IP addresses should be masked.

**Actual behavior:**
Inconsistent behaviour - seems to depend on what "EXTERNAL-IP" is showing for the service, but I'm not sure if that's effect or cause.
Almost all the time, the source IP is masked regardless of external traffic policy.
Almost all the time, traffic is routed to pods on all nodes, even when using Local policy
In rare cases, traffic times out or receives "Network is unreachable" even when using Cluster policy.

**Additional context / logs:**
It's hard to give accurate details, because the behaviour seems almost random.
Some of it seems to be related to "EXTERNAL-IP", but that can change for no reason (for instance, unrelated pod being created).
This seems likely related to #1969
