### ISSUE TITLE
config file support

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#2228]
In addition to configuring k3s with environment variables and cli arguments, k3s can also use a config file.

By default, values present in a `yaml` file located at `/etc/rancher/k3s/config.yaml` will be used on install.

An example of a basic `server` config file is below:

```yaml
# /etc/rancher/k3s/config.yaml
write-kubeconfig-mode: "0644"
tls-san:
  - "foo.local"
node-label:
  - "foo=bar"
  - "something=amazing"
```

In general, cli arguments map to their respective yaml key, with repeatable cli args being represented as yaml lists.

An identical configuration using solely cli arguments is shown below to demonstrate this:

```bash
k3s server \
  --write-kubeconfig-mode "0644"    \
  --tls-san "foo.local"             \
  --node-label "foo=bar"            \
  --node-label "something=amazing"
```

It is also possible to use both a configuration file and cli arguments.  In these situations, values will be loaded from both sources, but cli arguments will take precedence.  For repeatable arguments such as `--node-label`, the cli arguments will overwrite all values in the list.
