### ISSUE TITLE
Allow unsafe sysctls 

### ISSUE THREAD

**Issue by varac** [rancher/k3s#2233]
**Is your feature request related to a problem? Please describe.**

I need to turn off ipv6 in a certain pod. Before I was using rancher rke with `kubelet.extra_args.allowed-unsafe-sysctls` set to `net.ipv6.conf.all.disable_ipv6`, so I can then turn off ipv6 in pods easily.
I don't find a way to do this with k3s.

I.e. if I start a pod with following podSecurity:

```
podSecurityContext:                        
  sysctls:                                 
    - name: net.ipv6.conf.all.disable_ipv6 
      value: '1'                           
```
k3s will complain with: 

```
  Warning  SysctlForbidden  113s       kubelet, oas2.casita.local.moewe-altonah.de  forbidden sysctl: "net.ipv6.conf.all.disable_ipv6" not whitelisted
```

**Describe the solution you'd like**

I'd like to have a similar cl parameter to `k3s server` which I can use to allow unsafe systcls.

**Describe alternatives you've considered**

None so far, since I don't know of any workarounds.

**Additional context**

-
