### ISSUE TITLE
Question: How registries.yaml can have multiple repositories

### ISSUE THREAD

**Issue by mhewedy** [rancher/k3s#2259]
I have a single machine k3s installation for dev/test purposes.

The app images produced by our team are on GitLab.

I have the following `registries.yaml`:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://registry.gitlab.com"
configs:
  "registry.gitlab.com":
    auth:
      username: {{ username }}
      password: {{ gitlab_registry_token }}
```

It works fine to pull images from GitLab private registry, but it appears this registry is not working as a proxy for `docker.io`.

So, If I want to grab an image from docker.io (like `nginx`), I couldn't.

So my question how we can have multiple container repositories in registries.yaml

> I tried to add an entry for `"https://index.docker.io/v2/"` in the endpoints list but It seems it is not working

**Comment by brandond** [comment]
Does the nginx image exist on gitlab at `registry.gitlab.com/nginx:latest`? If you want to use your registry as a mirror for docker.io, the images need to have the exact same name.

**Comment by mhewedy** [comment]
the image doesn't exist on `registry.gitlab.com`.

The Gitlab registry contains only my project images. 
And I need to have Github for `rancher` and other images (`nginx` and others)

**Comment by brandond** [comment]
You've told it to use registry.gitlab.com as a mirror for docker.io. If that's not what you want, don'd do it. Did you mean to do something like this:

```yaml
mirrors:
  registry.gitlab.com:
    endpoint:
      - "https://registry.gitlab.com"
configs:
  registry.gitlab.com:
    auth:
      username: {{ username }}
      password: {{ gitlab_registry_token }}
```
