### ISSUE TITLE
Need to have a CIS profile that will have all active tests passed

### ISSUE THREAD

**Issue by maggieliu** [rancher/k3s#2288]
Need to have a CIS profile for k3s that will pass all active tests by default (tests can be skipped)

on master-head - `9addfe2`

- CIS v2 scan has failures when `cis-1.5-profile` is run on k3s imported clusters
- k3s imported cluster scan summary

```
summary:
    fail: 92
    notApplicable: 0
    pass: 0
    skip: 0
    total: 92
```
