### ISSUE TITLE
Prometheus not able to scrape cadvisor metrics 

### ISSUE THREAD

**Issue by clambin** [rancher/k3s#2289]
Not sure if I should be raising this on k3s or prometheus, but looks like a k3s-specific configuration issues.

**Environmental Info:**
K3s Version: 
k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Linux raspberrypi1 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

Cluster Configuration:
One master node with three worker nodes

**Describe the bug:**
I've added Prometheus to my k3s cluster.  However, Prometheus is not able to scrape the cadvisor metrics.  In Prometheus, I get the following error:

Endpoint:  http://kubernetes.default.svc:443/api/v1/nodes/raspberrypi/proxy/metrics/cadvisor 
Error:  server returned HTTP status 400 Bad Request

As you can see, I'm using http.  If I use https, I get a different error:

Get "https://kubernetes.default.svc:443/api/v1/nodes/raspberrypi/proxy/metrics/cadvisor": remote error: tls: internal error

Prometheus is able to scrape other metrics (apiserver, etc).  I can scrape cadvisor directly from the command line, though:

```
$ kubectl get --raw /api/v1/nodes/raspberrypi/proxy/metrics/cadvisor
# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="",cadvisorVersion="",dockerVersion="19.03.13",kernelVersion="5.4.51-v7l+",osVersion="Raspbian GNU/Linux 10 (buster)"} 1
# HELP container_cpu_load_average_10s Value of container cpu load average over the last 10 seconds.
# TYPE container_cpu_load_average_10s gauge
container_cpu_load_average_10s{container="",id="/",image="",name="",namespace="",pod=""} 0 1600679923884
...
```

Details on the Prometheus configuration:

1. Prometheus scraper config:

```
    - job_name: kubernetes-nodes
      # scheme: https  # remove if you want to scrape metrics on insecure port
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      metrics_path: /metrics/cadvisor
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
...
```

2. RBAC config

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
# Just an example, feel free to change it
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - services
  - endpoints
  - ingresses
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prom-rbac
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
```

and prometheus is started with that service account:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
```

Error messages in /var/log/pods/kube-system_metrics-server-7566d596c8-xjtm8_b6ab040a-0
fa9-4af6-bdb1-ce9f804aff1e/metrics-server:

```
2020-09-21T11:25:20.018270403+02:00 stderr F I0921 09:25:20.018054       1 log.go:172] http: TLS handshake error from 10.42.3.105:38534: tls: first record does not look like a TLS handshake
2020-09-21T11:25:35.019511017+02:00 stderr F I0921 09:25:35.019277       1 log.go:172] http: TLS handshake error from 10.42.3.105:38654: tls: first record does not look like a TLS handshake
2020-09-21T11:25:50.019602312+02:00 stderr F I0921 09:25:50.019277       1 log.go:172] http: TLS handshake error from 10.42.3.105:38774: tls: first record does not look like a TLS handshake
```

10.42.3.105 is the Prometheus pod, but not sure if it's related, or what the root cause is.

Still very new to k3s w/ prometheus, but I don't see any configuration that I may have missed.  If you need any more info, let me know.
