### ISSUE TITLE
Insecure registry does not support port 80

### ISSUE THREAD

**Issue by howdoicomputer** [rancher/k3s#2299]
**Environmental Info:**
K3s Version: 
k3s version v1.17.2+k3s1 (cdab19b0)

Node(s) CPU architecture, OS, and Version: 
Linux piekube-agent-01 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
1 master 2 agents
3 raspberry pi 4s
configured using k3sup

**Describe the bug:**
I deployed a private registry to my cluster (backed by NFS). It works if I'm using it as a client. I've assigned the service an address that is handled by metallb and pihole handles the DNS record for that registry for my internal network. The record for the registry is `docker-registry.home`.

I'm able to push and pull from my registry from my local workstation.

```
❯ docker push docker-registry.home/hello-world                                                                             17:04:30
The push refers to repository [docker-registry.home/hello-world]
9c27e219663c: Layer already exists
latest: digest: sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042 size: 525
```

However, with the `registries.yml` looking like this:

```
root@piekube-agent-01:/etc/rancher/k3s# cat registries.yml
mirrors:
  docker-registry.home:
    endpoint:
      - "http://docker-registry.home"
```

I'm unable to get a job to pull down the image.

Job error:

`
Failed to pull image "docker-registry.home/hello-world": rpc error: code = Unknown desc = failed to pull and unpack image "docker-registry.home/hello-world:latest": failed to resolve reference "docker-registry.home/hello-world:latest": failed to do request: Head https://docker-registry.home/v2/hello-world/manifests/latest: dial tcp 10.0.0.201:443: connect: no route to host
`

Job yml:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello
          image: docker-registry.home/hello-world
      restartPolicy: OnFailure
```

**Steps To Reproduce:**
See description.

**Expected behavior:**
That k3s would recognize that a `http://` endpoint shouldn't redirect to `https`.

**Actual behavior:**
k3s is trying to redirect to port 443

**Additional context / logs:**
I don't really wanna' setup TLS for my private registry. It is only accessible within my local LAN. It'd be nice if I didn't have to specify a port. Super, super low priority though.
