### ISSUE TITLE
[Documentation] Promote SELinux support (v1.19.4)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2473]
It's marked as experimental. It's nearly all there and pretty close to being certified. After we fix rancher/k3s#2240 and ship releases on or around 11/11 (upstream patches) we will take it out of experimental in docs.

This ONLY affects k3s version v1.19.4+k3s1 and newer. v1.18 and v1.17 branches will continue to have experimental support only. Reference the documentation for details: https://rancher.com/docs/k3s/latest/en/advanced/#selinux-support

**Comment by westurner** [comment]
k3s-ansible could be updated here as well: https://github.com/rancher/k3s-ansible/blob/721c3487027e42d30c60eb206e0fb5abfddd094f/roles/prereq/tasks/main.yml#L2-L5

OTOH something like this:

```yaml
- name: Set SELinux to disabled state
  selinux:
    state: disabled
  when:
    - not k3s_disable_selinux is defined or k3s_disable_selinux == False
    - ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
```

With this added to https://github.com/rancher/k3s-ansible/blob/master/inventory/sample/group_vars/all.yml :

```yaml
k3s_disable_selinux_variable: False
```
