### ISSUE TITLE
flag provided but not defined: -server https://<init server>:6443

### ISSUE THREAD

**Issue by FlexibleToast** [rancher/k3s#2488]
**Environmental Info:**
K3s Version: k3s version v1.19.3+k3s2 (f8a4547b)

Node(s) CPU architecture, OS, and Version: 
Linux pikubed-m1 5.4.0-1022-raspi #25-Ubuntu SMP PREEMPT Thu Oct 15 13:31:49 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
3 masters, 1 worker. Using the embedded HA provided by the new embedded etcd following instructions found here: https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Describe the bug:**
I've installed the first node setting a secret token using `export K3S_TOKEN=<a generated token>`, set the channel to latest, downloading the installation script and then running it as `/tmp/k3s.sh server --cluster-init`. This works fine. When I try to add the next two masters they both fail. I do the same export of token and channel, download the script, then run `/tmp/k3s.sh server --server https://<init server hostname>:6443`. This fails. Whenever k3s attempts to start the service fails. When looking at journalctl the output is `level=fatal msg="flag provided but not defined: -server https://pikubed-m0:6443"`. The service file looks like this:
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--server https://pikubed-m0:6443' \
```
When I add the agent machine I use the same previous steps and `/tmp/k3s.sh agent --server https://pikubed-m0:6443`. It appears to complete successfully, but when I run kubectl get nodes on the master it doesn't show up.

```
sudo kubectl get nodes
NAME         STATUS   ROLES         AGE   VERSION
pikubed-m0   Ready    etcd,master   67m   v1.19.3+k3s2
```

**Steps To Reproduce:**

- Installed K3s: I installed things using an ansible playbook

```
- name: Install k3s on first master
  command: 
    argv:
    - /tmp/k3s.sh 
    - server
    - --cluster-init
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
...
- name: Install k3s on masters
  command: 
    argv:
    - /tmp/k3s.sh 
    - server 
    - "--server https://{{ groups['masters'][0] }}:6443"
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
...
- name: Install k3s on workers
  command:
    argv:
    - /tmp/k3s.sh 
    - agent 
    - "--server https://{{ groups['masters'][0] }}:6443"
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
```

**Expected behavior:**
Second and third masters are successfully added to the cluster as etcd hosts, worker is added to the cluster.

**Actual behavior:**
Initial master successfully installes, k3s fails to start on other masters, worker doesn't connect to cluster.

**Comment by FlexibleToast** [comment]
I noticed in the docs that Ubuntu 20.04 isn't officially supported, so I also tried this with Ubuntu 18.04. This returned the exact same failed result.

**Comment by brandond** [comment]
The flag should be passed as '--server=https://pikubed-m0:6443' or '--server' 'https://pikubed-m0:6443' but not all quoted together with a space like you have it.

**Comment by FlexibleToast** [comment]
Oh interesting, I thought I tried that. Looking back at my previous commits it's clear that I did not though. I guess when looking at the example in the docs `K3S_TOKEN=SECRET k3s server --server https://<ip or hostname of server1>:6443` I thought that the --server was the option and the server url was the argument for that option. Hence why I put them on the same line in the Ansible playbook. I did try it without quotes on the same line originally and had the same error.
```
- name: Install k3s on masters
  command: 
    argv:
    - /tmp/k3s.sh 
    - server 
    - --server https://{{ groups['masters'][0] }}:6443
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
```
Maybe Ansible quotes them together when passing them on the same line like that though. I will modify and report back.

**Comment by FlexibleToast** [comment]
Thank you, this does appear to have worked.
```
sudo kubectl get nodes
NAME         STATUS   ROLES         AGE     VERSION
pikubed-m0   Ready    etcd,master   9m27s   v1.19.3+k3s2
pikubed-m1   Ready    etcd,master   3m19s   v1.19.3+k3s2
pikubed-m2   Ready    etcd,master   3m41s   v1.19.3+k3s2
pikubed-w0   Ready    <none>        3m6s    v1.19.3+k3s2
```
I changed the relevant Ansible task to this:
```
- name: Install k3s on masters
  command: 
    argv:
    - /tmp/k3s.sh 
    - server 
    - --server
    - https://{{ groups['masters'][0] }}:6443
  environment:
    K3S_TOKEN: '{{ k3s_token }}'
    INSTALL_K3S_CHANNEL: '{{ k3s_channel }}'
```
Interestingly it appeared to fail when the setup script was initially run, but after logging into the machine I checked and the k3s service was actually running and the nodes report back correctly. Not sure why it failed to start initially.
