### ISSUE TITLE
my container in k3s has an unexpected cpu.cfs_quota_us "-1"

### ISSUE THREAD

**Issue by vntbbb** [rancher/k3s#2500]
**Environmental Info:**
K3s Version: 
k3s version v1.17.9+k3s1 (000a361f)

Node(s) CPU architecture, OS, and Version: 
Linux k8s-master 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 masters, 2 workers

**Describe the bug:**

cpu.cfs_quota_us for container is not what I expect.

**Steps To Reproduce:**
- Installed K3s: 
my customized shell，but the cri is containerd by default.

**Expected behavior:**
[root@k8s-master busybox]# cat pod.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: docker.io/busybox:1.28.3
    imagePullPolicy: IfNotPresent
    command:
    - tail
    - -f
    - /dev/null
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
```
[root@k8s-master busybox]# kubectl apply -f pod.yaml 
pod/busybox created

I expect the value of cpu.cfs_quota_us is 20000.

**Actual behavior:**
[root@k8s-master busybox]# kubectl get pods busybox -o yaml |grep uid
  uid: 985909e4-c2c7-4996-a2a9-024d01856ec0
[root@k8s-master busybox]# crictl ps |grep busybox
2b529a168c250       8ac48589692a5       2 minutes ago        Running             busybox                    0                   61bd8c5690c6b
[root@k8s-master busybox]# cd /sys/fs/cgroup/cpu/kubepods/pod985909e4-c2c7-4996-a2a9-024d01856ec0/2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73/
[root@k8s-master 2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73]# pwd
/sys/fs/cgroup/cpu/kubepods/pod985909e4-c2c7-4996-a2a9-024d01856ec0/2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73
[root@k8s-master 2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73]# cat cpu.shares
204
[root@k8s-master 2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73]# cat cpu.cfs_period_us 
100000
[root@k8s-master 2b529a168c25071a6f95491c4be1b13f6234832b37d6c33c194fff29fd88db73]# cat cpu.cfs_quota_us 
-1

the real value of cpu.cfs_quota_us is -1 !!!!!?????
I am not sure wether this is a BUG or not, thanks.

**Additional context / logs:**
no more logs
