### ISSUE TITLE
Pass node labels into Pod as env. vars?

### ISSUE THREAD

**Issue by whillas** [rancher/k3s#2546]
**Is your feature request related to a problem? Please describe.**

We have 2 teams, one that uses k3s and another that uses docker. We have a pod that needs to post to a docker container on the same machine. I'm trying to get the machines external IP inside k3s so i don't have to hard code the IP for each server/agent I deploy to. 

I noticed that the the IP i want is a label on the Node. Is it possible to get node labels passed into a pod via environmental variables?

**Describe the solution you'd like**
Some way of getting this IP that i can reference in the pod

**Describe alternatives you've considered**
Can't find any info on this? Perhaps is info is already available?

**Comment by whillas** [comment]
OH, so you can use 
```
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
```
to get the hostname into the pod and its all good :)
