### ISSUE TITLE
CloudFlare - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by guigo2k** [rancher/k3s#2590]
We have `k3s` clusters in private subnets behind AWS load balancer and CloudFlare. With the deprecation of basic auth, we can't authenticate to the API server because of the CloudFlare certificate in front of the API server. Is there a way to workaround this?

**Environmental Info:**
K3s Version:  v1.19.3+k3s3

**Comment by brandond** [comment]
No, if you are offloading SSL there is not really a good way to handle this issue. You could put Rancher or something else in front of k3s as an auth and ssl-aware proxy, but even in that case you would not want to offload SSL to an external LB if you are going to use certificate auth.

**Comment by guigo2k** [comment]
Can we use token authentication with the `--token-auth-file` flag ?

**Comment by brandond** [comment]
You mean passing that through like `--kube-apiserver-arg=token-auth-file=/path/to/tokens`? That that should work.

**Comment by guigo2k** [comment]
Managed to get `k3s` working behind CloudFlare with token authentication. There are some interesting bits to it however.

First of all, port `6443` [is not supported by CloudFlare](https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy
), so we need to use the `--https-listen-port` flag to change the API server port. In our case, we're using port `8443`.

Second, we have to pass the `token-auth-file` argument to the API server using the `--kube-apiserver-arg` flag. 
```sh
export INSTALL_K3S_EXEC="--https-listen-port 8443 --kube-apiserver-arg token-auth-file=/etc/auth-token"

echo "xxxxxxxxxxxxxxxxxxxxx,default,default,system:masters" > /etc/auth-token

curl -sfL https://get.k3s.io | sh -s -
```

Now we can authenticate to the API server using a simple `kubeconfig` file like this:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://k3s.example.com:8443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    token: xxxxxxxxxxxxxxxxxxxxx
```
