### ISSUE TITLE
traefik.yaml reset to origin after reboot

### ISSUE THREAD

**Issue by dragonflylee** [rancher/k3s#2600]
**Environmental Info:**
K3s Version:  v1.19.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux nanopineo3 5.9.10-rockchip64 #20.11 SMP PREEMPT Mon Nov 23 13:36:07 CET 2020 aarch64 GNU/Linux

Cluster Configuration:
 single node

**Describe the bug:**
`/var/lib/rancher/k3s/server/manifests/traefik.yaml` reset to origin after reboot

**Steps To Reproduce:**
modify `/var/lib/rancher/k3s/server/manifests/traefik.yaml` as below

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  valuesContent: |-
    rbac:
      enabled: true
    ssl:
      enabled: true
      enforced: true
    acme:
      enabled: true
      staging: true
      email: admin@domain.com
      challengeType: dns-01
      dnsProvider:
        name: alidns
      domains:
        enabled: true
        domainsList:
          - main: "*.domain.com"
    dashboard:
      enabled: true
      domain: traefik.domain.com
    metrics:
      prometheus:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    image: "rancher/library-traefik"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
```

after reboot it reset to origin
