### ISSUE TITLE
Array values break helm chart manifests

### ISSUE THREAD

**Issue by ajodock** [rancher/k3s#338]
**Describe the bug**
I am trying to make some changes to the default Traefik manifest, but as soon as an array is added to the chart's settings the manifest watcher breaks.  The deployment is never started, and all further changes to the manifests directory stop working permanently (even if the manifest is removed and the server rebooted).

**To Reproduce**
Edit traefik.yaml and add an array.  Reproduced with both of the formats below or just a by adding `test: ['myvalue']`
```
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.64.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    acme.domains.domainsList: [{main: '*.example.com'}]`
```
or
```
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.64.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    acme.domains.domainsList:
    - main: "*.example.com"
```

Normally this fails silently, but with --debug enabled the logs complain about being unable to marshal the array (this error repeats forever)
```
time="2019-04-12T01:33:28.566148896Z" level=debug msg="REST PATCH apis/k3s.cattle.io/v1//traefik"
time="2019-04-12T01:33:28.572940620Z" level=debug msg="REST UPDATE apis/k3s.cattle.io/v1/kube-system/addons/traefik"
E0412 01:33:28.573403    1253 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: json: cannot unmarshal array into Go struct field HelmChartSpec.set of type int32
E0412 01:33:28.573921    1253 watcher.go:208] watch chan error: EOF
E0412 01:33:28.577821    1253 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: json: cannot unmarshal array into Go struct field HelmChartSpec.set of type int32
W0412 01:33:28.578055    1253 reflector.go:256] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.HelmChart ended with: very short watch: github.com/rancher/norman/controller/generic_controller.go:175: Unexpected watch close - watch lasted less than a second and no items received
E0412 01:33:28.578197    1253 watcher.go:208] watch chan error: EOF
time="2019-04-12T01:33:28.578569738Z" level=debug msg="AddonController calling handler addon-start kube-system/traefik"
time="2019-04-12T01:33:29.578376034Z" level=debug msg="REST LIST apis/k3s.cattle.io/v1//helmcharts"
E0412 01:33:29.583655    1253 reflector.go:125] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.HelmChart: json: cannot unmarshal array into Go struct field HelmChartSpec.set of type int32
E0412 01:33:29.735739    1253 watcher.go:208] watch chan error: EOF
time="2019-04-12T01:33:29.735999871Z" level=debug msg="Wrote ping"
time="2019-04-12T01:33:30.584032141Z" level=debug msg="REST LIST apis/k3s.cattle.io/v1//helmcharts"
E0412 01:33:30.587795    1253 reflector.go:125] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.HelmChart: json: cannot unmarshal array into Go struct field HelmChartSpec.set of type int32
```

**Expected behavior**
Expected helm chart deployment to update chart values, and to continue deploying manifests in the k3s server manifests directory.

**Additional context**
Running a fresh install of k3s on Ubuntu 18.04.2.  No special options other than --debug specified to the k3s server command.

**Comment by ajodock** [comment]
It looks like this is a problem with booleans as well.  The current traefik helm manifest shipped with k3s uses "true" instead of true, but if you use true it breaks the manifest watcher like the above array example.

If you use "true"/"false" instead it treats them as strings which means that `"false" == true`.  This makes it impossible to override any chart value that defaults to true.

Here is an example with acme.staging unset which defaults to false. [values.yaml](https://github.com/helm/charts/blob/master/stable/traefik/values.yaml)
```
root@k3s01:~/deploy# cat /var/lib/rancher/k3s/server/manifests/traefik.yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.64.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"


root@k3s01:~/deploy# kubectl get configmap/traefik -o yaml | grep acme
root@k3s01:~/deploy#
```
We can see that the acme section is missing from the configmap as expected.

However after forcing acme.enabled to "false" (which it already is by default), we can see that the chart is actually interpreting it as true.  Presumably because it is treating it as a string instead of a boolean.  We can see [here](https://github.com/helm/charts/blob/5379d141ccdff459fa5e9d542a17e5a527547735/stable/traefik/templates/configmap.yaml#L230) that the entire acme section should be missing like shown above when .Values.acme.enabled is false, but below you can see that after setting "false" the section gets created anyways.

```
root@k3s01:~/deploy# cat /var/lib/rancher/k3s/server/manifests/traefik.yaml 
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.64.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    acme.enabled: "false"


root@k3s01:~/deploy# kubectl get configmap/traefik -o yaml | grep acme
    [acme]
    storage = "/acme/acme.json"
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
root@k3s01:~/deploy#
```

**Comment by m4rcu5** [comment]
I'd also like to confirm that boolean values break HelmCharts.

In my example I like to disable the webhook on the `cert-manager` chart:
```
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  version: v0.7.0
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  set:
    ingressShim.defaultIssuerName: "letsencrypt-prod"
    ingressShim.defaultIssuerKind: "ClusterIssuer"
    webhook.enabled: false
```

The server's debug output is similar as mentioned by @ajodock:
```
DEBU[2019-04-12T15:33:45.821411150+02:00] AddonController calling handler addon-start kube-system/cert-manager 
DEBU[2019-04-12T15:33:45.821793903+02:00] Skipping existing deployment of /var/lib/rancher/k3s/server/manifests/coredns.yaml, check=true, checksum 76d5fed79105a989f8e02faea8c22f266b2f8f8b0cee18dcc8d645c1dc26524d=76d5fed79105a989f8e02faea8c22f266b2f8f8b0cee18dcc8d645c1dc26524d 
DEBU[2019-04-12T15:33:46.456802128+02:00] Wrote ping                                   
DEBU[2019-04-12T15:33:46.819815582+02:00] REST LIST apis/k3s.cattle.io/v1//helmcharts  
E0412 15:33:46.826600    7917 reflector.go:126] github.com/rancher/norman/controller/generic_controller.go:161: Failed to list *v1.HelmChart: json: cannot unmarshal bool into Go struct field HelmChartSpec.set of type int32
```

I have tried quoting the "false" value as well, throwing the following warning in the `helm-install` pod:
```
+ helm upgrade cert-manager cert-manager --namespace cert-manager --repo https://charts.jetstack.io --version v0.7.0 --set-string ingressShim.defaultIssuerKind=ClusterIssuer --set-string ingressShim.defaultIssuerName=letsencrypt-prod --set-string webhook.enabled=false
2019/04/12 13:51:08 Warning: Condition path 'webhook.enabled' for chart webhook returned non-bool value
```

**Comment by ibuildthecloud** [comment]
The `set` field is `map[string]string` so you must quote everything in the value because of how yaml works.  So "true" not true.  If this causes an issue with your chart then you can also use `valuesContent` as referred to in the README.md.  An example as below

```yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
spec:
  chart: stable/grafana
  targetNamespace: monitoring
  set:
    adminPassword: "NotVerySafePassword"
  valuesContent: |-
    image:
      tag: master
    env:
      GF_EXPLORE_ENABLED: true
    adminUser: admin
    sidecar:
      datasources:
        enabled: true
```

With valuesContent you can put any content and it should always work.  It's just a bit more verbose.
