### ISSUE TITLE
Resource limits does not work

### ISSUE THREAD

**Issue by mengyangGIT** [rancher/k3s#392]
**Describe the bug**
1.  deploy a pod and set the resources limit  cpu:200m.
2.  run the command "while true" in that container
3.  get the top info to see the cpu percent

**Expected behavior**
excepted : cpu 20%
but whatever i set to the limit ,cpu  percent  is always 100%.

**Additional context**

OS: centos 7  
kernel ver: 3.10.0-957.10.1.el7.x86_64
k3s ver: 0.4

**Comment by Duske** [comment]
When booting up k3s it logs `Disabling CPU quotas due to missing cpu.cfs_period_us`.
Maybe it's related to this issue and helps.

**Comment by joaovitor** [comment]
I got into this while executing this https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

This creates the pod but expected OOMKilled on the next section is not happening:

```shell
kubectl apply -f https://k8s.io/examples/pods/resource/memory-request-limit-2.yaml --namespace=mem-example
```
....

```shell
kubectl get pod memory-demo-2 --namespace=mem-example
```

**Comment by galal-hussein** [comment]
@mengyangGIT  I am not able to reproduce the issue with the latest k3s version, here are my steps:

- start k3s server
- install metrics server
- run the following yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
```
- run `kubectl top pods -n cpu-example`

Result:

I can see that the limit is honored correctly:
```
✗ k top pods cpu-demo -n cpu-example
NAME       CPU(cores)   MEMORY(bytes)   
cpu-demo   991m         1Mi
```

I also tried the example with exceeding the cpu limit:
```
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"
```
which requests 100 cpu, and the pod didn't start as expected:
```
k describe pods/cpu-demo-2 -n cpu-example
.....
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  27s (x5 over 6m24s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
```
