### ISSUE TITLE
Expand HelmChart documentation to cover more cases

### ISSUE THREAD

**Issue by proegssilb** [rancher/k3s#526]
**Is your feature request related to a problem? Please describe.**
I cannot find critical information about working with Helm in the [helm section of the readme](https://github.com/rancher/k3s#auto-deploying-manifests).

**Describe the solution you'd like**
The [helm section of the readme](https://github.com/rancher/k3s#auto-deploying-manifests) needs to be adapted to add the following information:
- How to install a chart from a third-party repository
- How to install a specific version of a chart

Ideally, there should be enough information to install cert-manager and rancher in the readme. But, the two bullet points above _should_ cover those two charts.

**Describe alternatives you've considered**
- I could install helm on my client machine, manually download the appropriate chart, and run with it. This is less repeatable, and not really the right answer for my case (nor should it be the go-to answer).
- I could manually locate the chart URL as proposed in Slack. I've spent days trying to figure out how to find the chart URL in a repeatable manner, and haven't found any documentation or blog posts. As such, this should not be the go-to answer for all charts. It's fine for internal charts or cases where the chart URL is known, but my case is not in that category. Furthermore, even if it is a common/recommended answer, it should be documented here, not in Slack (where messages vanish).

**Additional context**
I'm trying to automate installing & deploying k3os and the applications I'll be running on it. There will be steps that can't be done automatically. Two of the steps I'm doing are installing cert-manager and installing rancher, both from helm charts. Given the built-in operator for installing helm charts, I'd expect the common helm use cases to be automatable with a single manifest per chart.

If someone can provide the information I lack, I'm willing to attempt writing a pull request for this. Note that my writing style might not mesh with the rest of the readme.

**Comment by grstein** [comment]
I cant find how to install a bitnami chart too.

**Comment by digger18** [comment]
Try to download the **/index.yaml** file from the chart repository you are interested in, locate your chart and it's version and you will find the chart's tar.gz link.

Use that .tar.gz link in your HelmChart manifest under **.spec.chart**

For example:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: https://releases.rancher.com/server-charts/latest/rancher-2.2.4.tgz
  targetNamespace: cattle-system
  valuesContent: |-
    replicas: 1
    hostname: rancher.anv
```

**Comment by blake** [comment]
You should be able to install Rancher from Helm using the following chart.

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  targetNamespace: cattle-system
  valuesContent: |-
    replicas: 1
    hostname: rancher.local
```

Cert-manager will need to be installed prior to running this.

**Shameless plug** – I published an article, [Exploring the HelmChart custom resource in k3s](https://dev.to/blakec/exploring-the-helmchart-custom-resource-in-k3s-2l52), which should be helpful for people looking to understand this resource & write their own charts. I briefly mentioned using external repositories, but did not cover it in detail. Essentially, the `repo` field should just contain a path to the repository; the same URL used in `helm repo add`. Then you just reference the name of the chart in the `chart` key as seen in the above example.
