### ISSUE TITLE
V0.6 - Helmchart configMap not created 

### ISSUE THREAD

**Issue by zhiminwen** [rancher/k3s#551]
**Describe the bug**
When the helmchart spec is using valuesContent, the respective configmap "chart-values-..." is missing. Therefore the job pod cannot be created.

**To Reproduce**
Use the following helmchart yaml file
```
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: docker-registry
      namespace: kube-system
    spec:
      chart: stable/docker-registry
      targetNamespace: kube-system
      valuesContent: |-
        service:
          name: registry
          type: LoadBalancer
        persistence:
          enabled: true
        tlsSecretName: tls-secret-registry
```
