### ISSUE TITLE
Improve compatibility with Filebeat

### ISSUE THREAD

**Issue by sebschlue** [rancher/k3s#571]
It seems that Filebeat either cannot retrieve kubernetes metadata or cannot match log files to pods properly when running Filebeat outside of kubernetes cluster. Logs can be shipped to Elasticsearch but do not contain any Kubernetes Metadata.

k3s version v0.5.0
Filebeat version 7.1.1

The following works when using upstream k8s and docker (simplified for clarity):

```
filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~
    - add_host_metadata: ~
    - add_kubernetes_metadata:
        in_cluster: false
        host: <host>
        namespace: <namespace>
        kube_config: /root/.kube/config
```

I have tried to adapt this to k3s running with containerd:

```
filebeat.inputs:
- type: log
  paths:
    - /var/log/pods/*/*/*.log
  encoding: utf-8
  processors:
    - add_host_metadata: ~
    - add_kubernetes_metadata:
        in_cluster: false
        host: <host>
        namespace: <namespace>
        kube_config: /root/.kube/config
```

But this does not work regarding kubernetes metadata.

It seems that the filebeat -> k3s API connection works:

```
Jun 24 14:50:12 k3s-node01.lab filebeat[46402]: 2019-06-24T14:50:12.750+0200        INFO        kubernetes/util.go:71        kubernetes: Using node k3s-node01.lab provided in the config
Jun 24 14:50:12 k3s-node01.lab filebeat[46402]: 2019-06-24T14:50:12.750+0200        INFO        kubernetes/watcher.go:182        kubernetes: Performing a resource sync for *v1.PodList
Jun 24 14:50:12 k3s-node01.lab filebeat[46402]: 2019-06-24T14:50:12.762+0200        INFO        kubernetes/watcher.go:198        kubernetes: Resource sync done
```

But logs read from `/var/log/pods/*/*/*.log` are not being enriched with kubernetes metadata.

I am not sure if this is maybe a mere configuration issue and if not then I also don't know whose fault it is in the first place, maybe I need to open a filebeat ticket instead. But since k3s should be a drop-in-replacement for k8s, I create a ticket here first.

**Comment by pavel-mikhalchuk** [comment]
hey! do you have any updtes on this issue? tnx!

**Comment by sebschlue** [comment]
Here's a working example:

```
filebeat.inputs:

- type: container
  enabled: true
  symlinks: true
  stream: all
  paths:
    - "/var/log/containers/*.log"
  encoding: utf-8
  processors:
    - add_kubernetes_metadata:
        in_cluster: false
        kube_config: /root/.kube/config
        host: <host>
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
  multiline.pattern: '[[:space:]]+(at|\.{3}|Caused by)'
  multiline.negate: false
  multiline.match: after
````

See also https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/filebeat-kubernetes.yaml
