### ISSUE TITLE
Wrong interface selection on Vagrant

### ISSUE THREAD

**Issue by selcukusta** [rancher/k3s#72]
When trying to install k3s via Vagrant, Flannel selects the first network interface but the first one is using to bridge guest machines on Vagrant.

First solution is using flannel with external installation (with —no-flannel flag). My suggestion is, run the k3s server with “—iface=enp0s8” flag which will be used for flannel configuration or something like that.

**Comment by ibuildthecloud** [comment]
@selcukusta There is a `--node-ip x.x.x.x` flag, would that work?

**Comment by selcukusta** [comment]
hi @ibuildthecloud! Unfortunately, doesn't work. My cluster info:

```
master01 192.168.0.10
worker01 192.168.0.11
worker02 192.168.0.12
```

`sudo cat /run/flannel/subnet.env` output is;

```
FLANNEL_NETWORK=10.42.0.0/16
FLANNEL_SUBNET=10.42.1.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
It might be wrong, am I right?

**Comment by colby** [comment]
This is a documented behavior of kubelet, where it will select the default interface, which happens to be the NAT network of Vagrant. Try using `KUBELET_EXTRA_ARGS` to override that.

**Comment by selcukusta** [comment]
Yes, you're right. Two actions are needed. The first one is;

`sudo sed -i '9s/^/Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false --node-ip='"$1"'"\n/' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf` but kubelet service is embedded in k3s binary.

Another one is add `--iface=enp0s8` flag to flannel manifest file like that;

```
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.10.0-amd64
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=enp0s8
```
But the interface selection operation is embedded also. So I couldn't change them.
