### ISSUE TITLE
Pull image k8s.gcr.io/pause:3.1 again with it in local

### ISSUE THREAD

**Issue by xiyanxiyan10** [rancher/k3s#849]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**
install k3s with Release v0.9.1 by 

```
 curl -sfL https://get.k3s.io | sh -
```

Try to pull image  "k8s.gcr.io/pause:3.1" again when I deploy a deployment in k3s
But I already download this images in local in case of download fail in China

**To Reproduce**
docker pull registry.cn-beijing.aliyuncs.com/zhoujun/pause:3.1
docker tag registry.cn-beijing.aliyuncs.com/zhoujun/pause:3.1 k8s.gcr.io/pause:3.1

then 

```
k3s kubectl create -f demo.yml
```

demo.yml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: captcha-deployment
  name: captcha
  namespace: jojoquant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captcha
  template:
    metadata:
      labels:
        app: captcha
    spec:
      containers:
      - image: nginx
        name: captcha
        ports:
        - containerPort: 80
          protocol: TCP 
```

**Expected behavior**

```
[root@jojoquant k3s]# kubectl --namespace=jojoquant get event
LAST SEEN   TYPE      REASON                   OBJECT                         MESSAGE
111s        Warning   FailedCreatePodSandBox   pod/captcha-5f86dd7878-ss44n   Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout

```

**Screenshots**
It seems that k3s pull images k8s.gcr.io/pause:3.1 from Internet with It in local 

**Additional context**
