### ISSUE TITLE
local-path-provisioner failing to start because of missing clusterrole object

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#884]
**Version:**
v0.10.0-alpha1

**Describe the bug**
local-path-provisioner reports missing clusterrole object, even if the manifest is configured with correct clusterrole and clusterrolebinding.

This error is seen intermittently.

```
ERROR: logging before flag.Parse: E1009 21:47:05.681843       1 leaderelection.go:252] error retrieving resource lock kube-system/rancher.io-local-path: endpoints "rancher.io-local-path" is forbidden: User "system:serviceaccount:kube-system:local-path-provisioner-service-account" cannot get resource "endpoints" in API group "" in the namespace "kube-system": RBAC: clusterrole.rbac.authorization.k8s.io "local-path-provisioner-role" not found
```
```
root@ip-172-31-2-107:~# cat /var/lib/rancher/k3s/server/manifests/local-storage.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "persistentvolumes", "pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
- kind: ServiceAccount
  name: local-path-provisioner-service-account
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.11
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - start
        - --config
        - /etc/config/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/var/lib/rancher/k3s/storage"]
                }
                ]
        }
root@ip-172-31-2-107:~# 

```
**To Reproduce**
- Start k3s master
- run yaml file for nginx pv
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginxpv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpv
spec:
  selector:
    matchLabels:
      app: nginxpv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginxpv
    spec:
      containers:
      - image: nginx
        name: nginxpv
        volumeMounts:
        - name: nginxpv
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginxpv
        persistentVolumeClaim:
          claimName: nginxpv
```

**Expected behavior**
pv should be created and mounted within the pod.

**Actual behavior**
pod is on pending state and pv is not created. 
local-path-provisioner is showing error in the logs above.
