### ISSUE TITLE
Add option to no-deploy for helm

### ISSUE THREAD

**Issue by Prodian0013** [rancher/k3s#94]
**Is your feature request related to a problem? Please describe.**
Unable to deploy k3s without helm deployment.

**Describe the solution you'd like**
Currently the only options for no-deploy is coredns and servicelb.

Add helm to no-deploy option providing the ability to deploy the k3s without the helm deployment.

**Describe alternatives you've considered**
Manually delete the helm deployment.

**Additional context**

**Comment by ibuildthecloud** [comment]
@Prodian0013 two things 
1) We don't run tiller, so "disabling helm" doesn't really mean much, but I still understand.
2) We only run helm if some helm chart is set to deploy (currently the built in helm integration is undocumented, sorry)

So what you really want here is to disable traefik which is deployed using helm.  This can be done with `--no-deploy=traefik`  (sorry, I don't think this is documented).

Let me know if that works. Thanks.

**Comment by Prodian0013** [comment]
> @Prodian0013 two things
> 
> 1. We don't run tiller, so "disabling helm" doesn't really mean much, but I still understand.
> 2. We only run helm if some helm chart is set to deploy (currently the built in helm integration is undocumented, sorry)
> 
> So what you really want here is to disable traefik which is deployed using helm. This can be done with `--no-deploy=traefik` (sorry, I don't think this is documented).
> 
> Let me know if that works. Thanks.

Sorry yes I meant the traefik deployment.

Thanks for the quick response!

**Comment by erikwilson** [comment]
Please re-open @Prodian0013 with more info if this does not solve your issue.

**Comment by jwillmer** [comment]
> We only run helm if some helm chart is set to deploy (currently the built in helm integration is undocumented, sorry)

Could we also use the helm integration outside of the bootstrap process? So that I don't need to install helm manually.

**Comment by dewet22** [comment]
@jwillmer funny, I just found this thread because I was searching for documentation on the helm implementation. I use it fairly extensively already but it isn't quite clear how to redeploy updated charts (apply doesn't seem to have any effect) so I'm deleting & deploying all the time.

This is an example of metrics-server I use; you just deploy them like normal k8s objects:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: metrics-server
spec:
  chart: stable/metrics-server
  targetNamespace: metrics-server
  valuesContent: |-
    affinity:
      node: kubernetes.io/arch=arm
    image:
      repository: gcr.io/google_containers/metrics-server-arm:v0.3.2
```
